-- CW Manutenção — arquitetura funcional v2
-- Migração aditiva e reexecutável. Preserva demandas, códigos, usuários e mídias existentes.
begin;

create table if not exists public.cw_migracoes (
  versao text primary key,
  aplicado_em timestamptz not null default now()
);

-- Compatibilidade com instalações anteriores à arquitetura multiempresa.
alter table public.perfis add column if not exists email text;
alter table public.perfis add column if not exists loja text;
alter table public.perfis add column if not exists ativo boolean not null default true;
alter table public.perfis add column if not exists aprovacao text not null default 'aprovado';
alter table public.perfis add column if not exists aprovado_por uuid references auth.users(id);
alter table public.perfis add column if not exists aprovado_em timestamptz;
update public.perfis p set email=u.email from auth.users u where u.id=p.id and p.email is null;
update public.perfis set aprovacao='aprovado',ativo=true where aprovacao is null;
alter table public.perfis drop constraint if exists perfis_aprovacao_check;
alter table public.perfis add constraint perfis_aprovacao_check check(aprovacao in ('pendente','aprovado','rejeitado'));

create or replace function public.cw_org_atual() returns uuid language sql stable security definer set search_path=public as $$
  select organizacao_id from public.perfis where id=auth.uid() and ativo and aprovacao='aprovado';
$$;
create or replace function public.cw_admin() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.perfis where id=auth.uid() and ativo and aprovacao='aprovado' and papel='administrador');
$$;
create or replace function public.cw_acesso_org(org uuid) returns boolean language sql stable security definer set search_path=public as $$
  select coalesce(public.cw_admin() or (org is not null and org=public.cw_org_atual()),false);
$$;

-- Nomenclatura definitiva dos perfis.
alter table public.perfis drop constraint if exists perfis_papel_check;
update public.perfis set papel=case papel
  when 'empreendimento' then 'gestor'
  when 'gestor_manutencao' then 'gestor'
  when 'lojista' then 'usuario_padrao'
  when 'solicitante' then 'usuario_padrao'
  when 'manutencao' then 'tecnico'
  else papel end;
alter table public.perfis alter column papel set default 'usuario_padrao';
alter table public.perfis add constraint perfis_papel_check
  check (papel in ('administrador','gestor','auxiliar','tecnico','usuario_padrao'));

alter table public.permissoes_perfis drop constraint if exists permissoes_perfis_papel_check;
update public.permissoes_perfis set papel=case papel
  when 'gestor_manutencao' then 'gestor'
  when 'lojista' then 'usuario_padrao'
  else papel end;
alter table public.permissoes_perfis add constraint permissoes_perfis_papel_check
  check (papel in ('gestor','auxiliar','tecnico','usuario_padrao'));

alter table public.demandas add column if not exists codigo_solicitacao text;
alter table public.demandas add column if not exists natureza text;
alter table public.demandas add column if not exists centro_custo_id bigint;
alter table public.demandas add column if not exists operacao_id bigint;
alter table public.demandas add column if not exists finalizada_por_os boolean not null default false;

create table if not exists public.cw_sequencias (
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  ano integer not null,
  entidade text not null check (entidade in ('SOL','OS','EQP')),
  ultimo_numero integer not null default 0,
  primary key (organizacao_id,ano,entidade)
);
revoke all on public.cw_sequencias from public,anon,authenticated;

create table if not exists public.operacoes (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  nome text not null,
  codigo text,
  endereco text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  unique (organizacao_id,nome)
);

create table if not exists public.usuario_operacoes (
  usuario_id uuid not null references public.perfis(id) on delete cascade,
  operacao_id bigint not null references public.operacoes(id) on delete cascade,
  principal boolean not null default false,
  criado_em timestamptz not null default now(),
  primary key (usuario_id,operacao_id)
);

create table if not exists public.prioridades (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  nome text not null,
  ordem integer not null default 0,
  cor text,
  ativo boolean not null default true,
  unique (organizacao_id,nome)
);

create table if not exists public.naturezas_servico (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  nome text not null,
  ativo boolean not null default true,
  unique (organizacao_id,nome)
);

create table if not exists public.tipos_servico (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  nome text not null,
  ativo boolean not null default true,
  unique (organizacao_id,nome)
);

create table if not exists public.centros_custo (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  nome text not null,
  codigo text,
  ativo boolean not null default true,
  unique (organizacao_id,nome)
);

do $$ begin
  if not exists(select 1 from pg_constraint where conname='demandas_centro_custo_fk') then
    alter table public.demandas add constraint demandas_centro_custo_fk foreign key(centro_custo_id) references public.centros_custo(id);
  end if;
  if not exists(select 1 from pg_constraint where conname='demandas_operacao_fk') then
    alter table public.demandas add constraint demandas_operacao_fk foreign key(operacao_id) references public.operacoes(id);
  end if;
end $$;

create table if not exists public.prestadores (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  tipo_vinculo text not null check (tipo_vinculo in ('proprio','terceirizado')),
  tipo_pessoa text not null default 'juridica' check (tipo_pessoa in ('fisica','juridica')),
  nome text not null,
  cpf_cnpj text,
  email text,
  telefone text,
  especialidades text[] not null default '{}',
  observacoes text,
  usuario_tecnico_id uuid references public.perfis(id),
  ativo boolean not null default true,
  criado_por uuid references auth.users(id),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.prestador_documentos (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  prestador_id bigint not null references public.prestadores(id) on delete cascade,
  nome text not null,
  storage_path text not null,
  mime_type text,
  tamanho_bytes bigint,
  criado_por uuid references auth.users(id),
  criado_em timestamptz not null default now()
);

create table if not exists public.ativos (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  operacao_id bigint references public.operacoes(id),
  ativo_pai_id bigint references public.ativos(id),
  codigo text,
  nome text not null,
  categoria text,
  fabricante text,
  modelo text,
  numero_serie text,
  local text,
  data_aquisicao date,
  valor_aquisicao numeric(14,2),
  garantia_ate date,
  especificacoes jsonb not null default '{}'::jsonb,
  ativo boolean not null default true,
  criado_por uuid references auth.users(id),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (organizacao_id,codigo)
);

create table if not exists public.ativo_arquivos (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  ativo_id bigint not null references public.ativos(id) on delete cascade,
  nome text not null,
  storage_path text not null,
  mime_type text,
  tamanho_bytes bigint,
  criado_por uuid references auth.users(id),
  criado_em timestamptz not null default now()
);

create table if not exists public.planos_manutencao (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  ativo_id bigint not null references public.ativos(id) on delete cascade,
  nome text not null,
  descricao text,
  periodicidade_dias integer not null check (periodicidade_dias>0),
  proxima_execucao date not null,
  antecedencia_dias integer not null default 7 check (antecedencia_dias>=0),
  prestador_id bigint references public.prestadores(id),
  executor_id uuid references public.perfis(id),
  ativo boolean not null default true,
  criado_por uuid references auth.users(id),
  criado_em timestamptz not null default now()
);

create table if not exists public.ordens_servico (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  codigo text,
  solicitacao_id bigint references public.demandas(id) on delete set null,
  plano_manutencao_id bigint references public.planos_manutencao(id) on delete set null,
  ativo_id bigint references public.ativos(id) on delete set null,
  prestador_id bigint references public.prestadores(id) on delete set null,
  executor_id uuid references public.perfis(id) on delete set null,
  centro_custo_id bigint references public.centros_custo(id) on delete set null,
  titulo text not null,
  natureza text,
  prioridade text not null default 'A definir',
  local text,
  descricao text,
  status text not null default 'Aberta' check(status in ('Aberta','Planejada','Aguardando execução','Em execução','Pausada','Concluída','Cancelada')),
  inicio_previsto timestamptz,
  fim_previsto timestamptz,
  inicio_real timestamptz,
  fim_real timestamptz,
  descricao_execucao text,
  observacoes_executor text,
  aceite_status text not null default 'pendente' check(aceite_status in ('pendente','aceito','recusado','dispensado')),
  aceite_por uuid references public.perfis(id),
  aceite_em timestamptz,
  aceite_observacao text,
  avaliacao smallint check(avaliacao between 1 and 5),
  criado_por uuid not null references auth.users(id),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  concluido_em timestamptz,
  unique (organizacao_id,codigo)
);

create table if not exists public.ordens_servico_custos (
  ordem_servico_id bigint primary key references public.ordens_servico(id) on delete cascade,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  custo_mao_obra numeric(14,2) not null default 0,
  custo_materiais numeric(14,2) not null default 0,
  outros_custos numeric(14,2) not null default 0,
  observacoes text,
  atualizado_por uuid references auth.users(id),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.ordem_servico_materiais (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  ordem_servico_id bigint not null references public.ordens_servico(id) on delete cascade,
  descricao text not null,
  quantidade numeric(12,3) not null default 1,
  unidade text,
  valor_unitario numeric(14,2),
  criado_em timestamptz not null default now()
);

create table if not exists public.ordem_servico_arquivos (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  ordem_servico_id bigint not null references public.ordens_servico(id) on delete cascade,
  etapa text not null check(etapa in ('antes','durante','depois','documento')),
  nome text not null,
  storage_path text not null,
  mime_type text,
  tamanho_bytes bigint,
  criado_por uuid references auth.users(id),
  criado_em timestamptz not null default now()
);

create table if not exists public.historico_ordens_servico (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  ordem_servico_id bigint not null references public.ordens_servico(id) on delete cascade,
  usuario_id uuid references auth.users(id),
  acao text not null,
  detalhes jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create table if not exists public.notificacoes (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id) on delete cascade,
  usuario_id uuid references public.perfis(id) on delete cascade,
  titulo text not null,
  mensagem text not null,
  referencia_tipo text,
  referencia_id bigint,
  lida_em timestamptz,
  criado_em timestamptz not null default now()
);

create or replace function public.cw_proximo_codigo(p_org uuid,p_entidade text,p_data date default current_date)
returns text language plpgsql security definer set search_path=public as $$
declare n integer; v_ano integer:=extract(year from p_data);
begin
  if p_entidade not in ('SOL','OS','EQP') then raise exception 'Entidade inválida'; end if;
  insert into public.cw_sequencias(organizacao_id,ano,entidade,ultimo_numero)
  values(p_org,v_ano,p_entidade,1)
  on conflict(organizacao_id,ano,entidade) do update set ultimo_numero=public.cw_sequencias.ultimo_numero+1
  returning ultimo_numero into n;
  return case when p_entidade='EQP' then format('EQP-%s',lpad(n::text,4,'0'))
    else format('%s-%s-%s',p_entidade,v_ano,lpad(n::text,3,'0')) end;
end $$;

create or replace function public.cw_preparar_solicitacao_v2() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if new.codigo_solicitacao is null then new.codigo_solicitacao:=public.cw_proximo_codigo(new.organizacao_id,'SOL',coalesce(new.criado_em,now())::date); end if;
  return new;
end $$;
drop trigger if exists cw_preparar_solicitacao_v2 on public.demandas;
create trigger cw_preparar_solicitacao_v2 before insert on public.demandas
for each row execute function public.cw_preparar_solicitacao_v2();

-- Códigos antigos permanecem; apenas completa a nova identificação em ordem cronológica.
do $$ declare r record; begin
  for r in select id,organizacao_id,criado_em from public.demandas where codigo_solicitacao is null order by organizacao_id,criado_em,id
  loop update public.demandas set codigo_solicitacao=public.cw_proximo_codigo(r.organizacao_id,'SOL',r.criado_em::date) where id=r.id; end loop;
end $$;

create or replace function public.cw_preparar_os() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is not null and not public.cw_acesso_org(new.organizacao_id) then raise exception 'Sem acesso ao empreendimento'; end if;
  if auth.uid() is not null and not public.tem_permissao_usuario('os_criar') then raise exception 'Sem permissão para criar ordem de serviço'; end if;
  new.criado_por:=coalesce(new.criado_por,auth.uid());
  if new.codigo is null then new.codigo:=public.cw_proximo_codigo(new.organizacao_id,'OS',coalesce(new.criado_em,now())::date); end if;
  return new;
end $$;
drop trigger if exists cw_preparar_os on public.ordens_servico;
create trigger cw_preparar_os before insert on public.ordens_servico for each row execute function public.cw_preparar_os();

create or replace function public.cw_gerar_os_solicitacao(p_solicitacao bigint)
returns public.ordens_servico language plpgsql security definer set search_path=public as $$
declare d public.demandas%rowtype; resultado public.ordens_servico%rowtype;
begin
  select * into d from public.demandas where id=p_solicitacao;
  if d.id is null or not public.cw_acesso_org(d.organizacao_id) or not public.tem_permissao_usuario('os_criar') then raise exception 'Solicitação não encontrada ou sem permissão'; end if;
  insert into public.ordens_servico(organizacao_id,solicitacao_id,titulo,natureza,prioridade,local,descricao,inicio_previsto,fim_previsto,criado_por)
  values(d.organizacao_id,d.id,d.titulo,coalesce(d.natureza,case when d.tipo_demanda='preventiva' then 'Preventiva' else 'Corretiva' end),d.prioridade,d.local,d.observacoes,
    coalesce(d.agendamento_em,d.prazo::timestamptz),coalesce(d.agendamento_em,d.prazo::timestamptz),auth.uid()) returning * into resultado;
  return resultado;
end $$;

create or replace function public.cw_concluir_os(p_os bigint,p_descricao text,p_observacoes text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare os public.ordens_servico%rowtype; abertas integer; perguntar boolean:=false;
begin
  select * into os from public.ordens_servico where id=p_os for update;
  if os.id is null or not public.cw_acesso_org(os.organizacao_id) or not public.tem_permissao_usuario('os_concluir') then raise exception 'OS não encontrada ou sem permissão'; end if;
  if nullif(trim(p_descricao),'') is null then raise exception 'Informe a descrição da execução'; end if;
  update public.ordens_servico set status='Concluída',descricao_execucao=trim(p_descricao),observacoes_executor=nullif(trim(p_observacoes),''),fim_real=coalesce(fim_real,now()),concluido_em=now() where id=p_os;
  if os.solicitacao_id is not null then
    select count(*) into abertas from public.ordens_servico where solicitacao_id=os.solicitacao_id and id<>p_os and status not in ('Concluída','Cancelada');
    perguntar:=abertas=0;
  end if;
  return jsonb_build_object('ordem_servico_id',p_os,'solicitacao_id',os.solicitacao_id,'ultima_os',perguntar,'perguntar_finalizacao',perguntar);
end $$;

create or replace function public.cw_finalizar_solicitacao_por_os(p_solicitacao bigint,p_finalizar boolean)
returns void language plpgsql security definer set search_path=public as $$
declare d public.demandas%rowtype;
begin
  select * into d from public.demandas where id=p_solicitacao for update;
  if d.id is null or not public.cw_acesso_org(d.organizacao_id) or not public.tem_permissao_usuario('solicitacao_alterar_status') then raise exception 'Sem permissão'; end if;
  if exists(select 1 from public.ordens_servico where solicitacao_id=p_solicitacao and status not in ('Concluída','Cancelada')) then raise exception 'Existem ordens de serviço em aberto'; end if;
  if p_finalizar then update public.demandas set status='Concluído',finalizada_por_os=true where id=p_solicitacao; end if;
end $$;

create or replace function public.cw_registrar_aceite_os(p_os bigint,p_aceitar boolean,p_observacao text default null,p_avaliacao integer default null)
returns void language plpgsql security definer set search_path=public as $$
declare os public.ordens_servico%rowtype;
begin
  select * into os from public.ordens_servico where id=p_os for update;
  if os.id is null or not public.cw_acesso_org(os.organizacao_id) then raise exception 'OS não encontrada'; end if;
  if not (public.tem_permissao_usuario('os_aceitar') or exists(select 1 from public.demandas d where d.id=os.solicitacao_id and d.criado_por=auth.uid())) then raise exception 'Sem permissão para registrar aceite'; end if;
  if not p_aceitar and nullif(trim(p_observacao),'') is null then raise exception 'Informe o motivo da recusa'; end if;
  update public.ordens_servico set aceite_status=case when p_aceitar then 'aceito' else 'recusado' end,
    aceite_por=auth.uid(),aceite_em=now(),aceite_observacao=nullif(trim(p_observacao),''),avaliacao=case when p_aceitar then p_avaliacao else null end,
    status=case when p_aceitar then status else 'Em execução' end,concluido_em=case when p_aceitar then concluido_em else null end where id=p_os;
end $$;

create or replace function public.cw_gerar_os_programadas(p_data date default current_date)
returns integer language plpgsql security definer set search_path=public as $$
declare plano public.planos_manutencao%rowtype; total integer:=0;
begin
  if auth.uid() is not null and not public.cw_admin() then raise exception 'Rotina exclusiva da administração'; end if;
  for plano in select * from public.planos_manutencao p where p.ativo and p.proxima_execucao-p.antecedencia_dias<=p_data
  loop
    if not exists(select 1 from public.ordens_servico o where o.plano_manutencao_id=plano.id and o.inicio_previsto::date=plano.proxima_execucao) then
      insert into public.ordens_servico(organizacao_id,plano_manutencao_id,ativo_id,prestador_id,executor_id,titulo,natureza,status,inicio_previsto,fim_previsto,criado_por)
      values(plano.organizacao_id,plano.id,plano.ativo_id,plano.prestador_id,plano.executor_id,plano.nome,'Preventiva','Planejada',plano.proxima_execucao,plano.proxima_execucao,coalesce(plano.criado_por,(select id from public.perfis where organizacao_id=plano.organizacao_id and papel='gestor' and ativo limit 1)));
      total:=total+1;
    end if;
    update public.planos_manutencao set proxima_execucao=proxima_execucao+periodicidade_dias where id=plano.id;
  end loop;
  return total;
end $$;

-- Quando pg_cron estiver disponível no projeto, agenda a geração diária sem duplicar jobs.
do $$ begin
  if to_regnamespace('cron') is not null and not exists(select 1 from cron.job where jobname='cw-os-programadas') then
    perform cron.schedule('cw-os-programadas','15 3 * * *','select public.cw_gerar_os_programadas(current_date)');
  end if;
exception when insufficient_privilege or undefined_table or undefined_function then null;
end $$;

-- Perfis fixos: administrador é global; gestor é completo dentro da própria empresa.
create or replace function public.cw_admin() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.perfis where id=auth.uid() and ativo and aprovacao='aprovado' and papel='administrador');
$$;
create or replace function public.tem_permissao_usuario(acao_consultada text) returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.perfis p where p.id=auth.uid() and p.ativo and p.aprovacao='aprovado' and (
    p.papel in ('administrador','gestor') or exists(select 1 from public.permissoes_perfis r where r.organizacao_id=p.organizacao_id and r.papel=p.papel and r.acao=acao_consultada and r.permitido)
  ));
$$;
create or replace function public.cw_matriz(org uuid) returns boolean language sql stable security definer set search_path=public as $$
  select public.cw_admin() and public.cw_acesso_org(org);
$$;
create or replace function public.pode_gerenciar(org uuid) returns boolean language sql stable security definer set search_path=public as $$
  select public.cw_acesso_org(org) and public.tem_permissao_usuario('usuarios_gerenciar');
$$;
create or replace function public.pode_visualizar_demanda(demanda bigint) returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.demandas d where d.id=demanda and public.cw_acesso_org(d.organizacao_id) and
    (public.tem_permissao_usuario('solicitacao_visualizar_todas') or
      (d.criado_por=auth.uid() and public.tem_permissao_usuario('solicitacao_visualizar_proprias'))));
$$;
create or replace function public.cw_editar_demanda(demanda bigint) returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.demandas d where d.id=demanda and public.cw_acesso_org(d.organizacao_id) and
    (public.tem_permissao_usuario('solicitacao_editar') or
      (d.criado_por=auth.uid() and public.tem_permissao_usuario('solicitacao_editar_proprias'))));
$$;

create or replace function public.criar_perfil_usuario() returns trigger language plpgsql security definer set search_path=public as $$
declare org uuid;
begin
  begin org:=(new.raw_user_meta_data->>'organizacao_id')::uuid; exception when invalid_text_representation then org:=null; end;
  if org is null or not exists(select 1 from public.organizacoes where id=org) then
    org:=(select id from public.organizacoes order by criado_em limit 1);
  end if;
  insert into public.perfis(id,organizacao_id,nome,email,papel,ativo,aprovacao)
  values(new.id,org,coalesce(nullif(trim(new.raw_user_meta_data->>'nome'),''),split_part(new.email,'@',1)),new.email,'usuario_padrao',false,'pendente');
  return new;
end $$;
drop trigger if exists ao_criar_usuario on auth.users;
create trigger ao_criar_usuario after insert on auth.users for each row execute function public.criar_perfil_usuario();

create or replace function public.cw_pode_gerenciar_usuario(p_org uuid,p_usuario uuid,p_papel text)
returns boolean language sql stable security definer set search_path=public as $$
  select public.cw_acesso_org(p_org) and (
    (public.cw_admin() and p_papel in ('administrador','gestor','auxiliar','tecnico','usuario_padrao')) or
    (exists(select 1 from public.perfis where id=auth.uid() and papel='gestor' and ativo and aprovacao='aprovado' and organizacao_id=p_org)
      and p_papel in ('auxiliar','tecnico','usuario_padrao')
      and (p_usuario is null or exists(select 1 from public.perfis where id=p_usuario and organizacao_id=p_org and papel in ('auxiliar','tecnico','usuario_padrao'))))
  );
$$;

create or replace function public.cw_salvar_usuario(p_usuario uuid,p_nome text,p_email text,p_loja text,p_papel text,p_ativo boolean,p_aprovacao text)
returns void language plpgsql security definer set search_path=public as $$
declare alvo public.perfis%rowtype;
begin
  select * into alvo from public.perfis where id=p_usuario for update;
  if alvo.id is null or not public.cw_pode_gerenciar_usuario(alvo.organizacao_id,p_usuario,p_papel) then raise exception 'Sem permissão para alterar este usuário'; end if;
  if p_usuario=auth.uid() and (p_papel<>alvo.papel or not p_ativo or p_aprovacao<>'aprovado') then raise exception 'Não altere seu próprio perfil ou acesso'; end if;
  if p_aprovacao not in ('pendente','aprovado','rejeitado') or p_ativo is null or nullif(trim(p_nome),'') is null then raise exception 'Dados inválidos'; end if;
  update public.perfis set nome=trim(p_nome),email=trim(p_email),loja=nullif(trim(p_loja),''),papel=p_papel,
    aprovacao=p_aprovacao,ativo=(p_ativo and p_aprovacao='aprovado'),
    aprovado_por=case when p_aprovacao='aprovado' and alvo.aprovacao<>'aprovado' then auth.uid() else aprovado_por end,
    aprovado_em=case when p_aprovacao='aprovado' and alvo.aprovacao<>'aprovado' then now() else aprovado_em end where id=p_usuario;
end $$;

create or replace function public.cw_guardar_demanda() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then return case when tg_op='DELETE' then old else new end; end if;
  if tg_op='INSERT' then
    if not public.cw_acesso_org(new.organizacao_id) or not public.tem_permissao_usuario('solicitacao_criar') then raise exception 'Sem permissão neste empreendimento'; end if;
    new.criado_por:=auth.uid(); new.criado_em:=now();
    new.status:=case new.tipo_demanda when 'corretiva' then 'Registrado' when 'agendamento' then 'Aguardando aprovação' else 'Agendado' end;
    if not public.tem_permissao_usuario('solicitacao_alterar_status') then new.prioridade:='A definir'; new.responsavel:=null; new.prazo:=null; end if;
    return new;
  end if;
  if not public.cw_acesso_org(old.organizacao_id) then raise exception 'Sem acesso ao empreendimento'; end if;
  if tg_op='DELETE' then
    if not public.tem_permissao_usuario('solicitacao_excluir') then raise exception 'Sem permissão para excluir'; end if;
    return old;
  end if;
  if not public.cw_editar_demanda(old.id) then raise exception 'Sem permissão para editar'; end if;
  new.organizacao_id:=old.organizacao_id; new.criado_por:=old.criado_por; new.criado_em:=old.criado_em;
  new.codigo:=old.codigo; new.codigo_solicitacao:=old.codigo_solicitacao; new.tipo_demanda:=old.tipo_demanda;
  if not public.tem_permissao_usuario('solicitacao_alterar_status') then
    new.status:=old.status; new.prioridade:=old.prioridade; new.responsavel:=old.responsavel; new.prazo:=old.prazo;
  end if;
  return new;
end $$;
drop trigger if exists cw_guardar_demanda on public.demandas;
create trigger cw_guardar_demanda before insert or update or delete on public.demandas for each row execute function public.cw_guardar_demanda();

create or replace function public.criar_demanda_empresa(p_organizacao_id uuid,p_titulo text,p_local text,p_observacoes text,p_tipo_demanda text,p_agendamento_em timestamptz,p_empresa_prestador text,p_prioridade text,p_responsavel text,p_prazo date,p_observacoes_adicionais text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare demanda_id bigint; status_inicial text;
begin
  if not public.cw_acesso_org(p_organizacao_id) or not public.tem_permissao_usuario('solicitacao_criar') then raise exception 'Sem permissão para criar solicitações neste empreendimento'; end if;
  if p_tipo_demanda not in ('corretiva','agendamento','preventiva') then raise exception 'Tipo de solicitação inválido'; end if;
  if nullif(trim(p_titulo),'') is null or nullif(trim(p_local),'') is null then raise exception 'Tipo e local são obrigatórios'; end if;
  if p_tipo_demanda in ('corretiva','preventiva') and nullif(trim(p_observacoes),'') is null then raise exception 'A descrição é obrigatória'; end if;
  if p_tipo_demanda in ('agendamento','preventiva') and (p_agendamento_em is null or nullif(trim(p_empresa_prestador),'') is null) then raise exception 'Data prevista e prestador/responsável são obrigatórios'; end if;
  status_inicial:=case p_tipo_demanda when 'corretiva' then 'Registrado' when 'agendamento' then 'Aguardando aprovação' else 'Agendado' end;
  insert into public.demandas(organizacao_id,titulo,categoria,local,prioridade,responsavel,status,prazo,observacoes,observacoes_adicionais,criado_por,tipo_demanda,agendamento_em,empresa_prestador,tipo_servico)
  values(p_organizacao_id,trim(p_titulo),'Manutenção',trim(p_local),case when public.tem_permissao_usuario('solicitacao_alterar_status') then coalesce(nullif(trim(p_prioridade),''),'A definir') else 'A definir' end,
    case when public.tem_permissao_usuario('solicitacao_alterar_status') then nullif(trim(p_responsavel),'') end,status_inicial,
    case when public.tem_permissao_usuario('solicitacao_alterar_status') then p_prazo end,nullif(trim(p_observacoes),''),nullif(trim(p_observacoes_adicionais),''),auth.uid(),p_tipo_demanda,p_agendamento_em,nullif(trim(p_empresa_prestador),''),trim(p_titulo)) returning id into demanda_id;
  return jsonb_build_object('id',demanda_id);
end $$;
revoke all on function public.criar_demanda_empresa(uuid,text,text,text,text,timestamptz,text,text,text,date,text) from public,anon;
grant execute on function public.criar_demanda_empresa(uuid,text,text,text,text,timestamptz,text,text,text,date,text) to authenticated;

-- Amplia a matriz apenas para os três perfis configuráveis.
insert into public.permissoes_perfis(organizacao_id,papel,acao,permitido)
select o.id,r.papel,a.acao,case
  when r.papel='auxiliar' then a.acao in ('solicitacao_visualizar_todas','solicitacao_criar','solicitacao_editar','solicitacao_alterar_status','os_visualizar_todas','os_criar','os_editar','os_concluir','os_aceitar','ativos_visualizar','prestadores_visualizar','prestadores_editar','relatorios_emitir','custos_visualizar','custos_editar')
  when r.papel='tecnico' then a.acao in ('solicitacao_visualizar_todas','os_visualizar_todas','ativos_visualizar','historico_visualizar')
  else a.acao in ('solicitacao_criar','solicitacao_visualizar_proprias','solicitacao_editar_proprias','os_visualizar_resumo','os_aceitar','galeria_visualizar') end
from public.organizacoes o
cross join (values('auxiliar'),('tecnico'),('usuario_padrao')) r(papel)
cross join (values
 ('solicitacao_visualizar_todas'),('solicitacao_visualizar_proprias'),('solicitacao_criar'),('solicitacao_editar'),('solicitacao_editar_proprias'),('solicitacao_alterar_status'),('solicitacao_excluir'),
 ('os_visualizar_todas'),('os_visualizar_resumo'),('os_criar'),('os_editar'),('os_concluir'),('os_cancelar'),('os_aceitar'),
 ('ativos_visualizar'),('ativos_editar'),('planos_editar'),('prestadores_visualizar'),('prestadores_editar'),('usuarios_gerenciar'),('configuracoes_editar'),
 ('relatorios_emitir'),('custos_visualizar'),('custos_editar'),('historico_visualizar'),('galeria_visualizar'),('galeria_excluir')
) a(acao) on conflict(organizacao_id,papel,acao) do nothing;

-- Substitui as políticas das solicitações pelo vocabulário definitivo.
do $$ declare p record; begin
  for p in select policyname from pg_policies where schemaname='public' and tablename='demandas'
  loop execute format('drop policy %I on public.demandas',p.policyname); end loop;
end $$;
create policy cw_solicitacao_select on public.demandas for select to authenticated using(public.pode_visualizar_demanda(id));
create policy cw_solicitacao_insert on public.demandas for insert to authenticated with check(criado_por=auth.uid() and public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('solicitacao_criar'));
create policy cw_solicitacao_update on public.demandas for update to authenticated using(public.cw_editar_demanda(id)) with check(public.cw_editar_demanda(id));
create policy cw_solicitacao_delete on public.demandas for delete to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('solicitacao_excluir'));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('cw-arquivos','cw-arquivos',false,52428800,array['image/jpeg','image/png','image/webp','video/mp4','application/pdf'])
on conflict(id) do update set public=false;
create or replace function public.cw_storage_permitido(bucket text,caminho text,acao text) returns boolean language plpgsql stable security definer set search_path=public as $$
declare demanda bigint; org uuid;
begin
  if bucket='cw-anexos' then
    begin demanda:=split_part(caminho,'/',1)::bigint; exception when others then return false; end;
    if acao='select' then return public.pode_visualizar_demanda(demanda); end if;
    return public.cw_editar_demanda(demanda) and (acao<>'delete' or public.tem_permissao_usuario('galeria_excluir'));
  elsif bucket in ('cw-logos','cw-arquivos') then
    begin org:=split_part(caminho,'/',1)::uuid; exception when others then return false; end;
    if acao='select' then return public.cw_acesso_org(org); end if;
    return public.cw_acesso_org(org) and (case when bucket='cw-logos' then public.tem_permissao_usuario('configuracoes_editar') else public.tem_permissao_usuario('galeria_visualizar') end);
  end if;
  return false;
end $$;
drop policy if exists cw_storage_guard_select_v2 on storage.objects;
drop policy if exists cw_storage_guard_insert_v2 on storage.objects;
drop policy if exists cw_storage_guard_update_v2 on storage.objects;
drop policy if exists cw_storage_guard_delete_v2 on storage.objects;
create policy cw_storage_guard_select_v2 on storage.objects as restrictive for select to authenticated using(bucket_id not in ('cw-anexos','cw-logos','cw-arquivos') or public.cw_storage_permitido(bucket_id,name,'select'));
create policy cw_storage_guard_insert_v2 on storage.objects as restrictive for insert to authenticated with check(bucket_id not in ('cw-anexos','cw-logos','cw-arquivos') or public.cw_storage_permitido(bucket_id,name,'insert'));
create policy cw_storage_guard_update_v2 on storage.objects as restrictive for update to authenticated using(bucket_id not in ('cw-anexos','cw-logos','cw-arquivos') or public.cw_storage_permitido(bucket_id,name,'update')) with check(bucket_id not in ('cw-anexos','cw-logos','cw-arquivos') or public.cw_storage_permitido(bucket_id,name,'update'));
create policy cw_storage_guard_delete_v2 on storage.objects as restrictive for delete to authenticated using(bucket_id not in ('cw-anexos','cw-logos','cw-arquivos') or public.cw_storage_permitido(bucket_id,name,'delete'));

-- RLS: toda tabela operacional leva organizacao_id e valida o empreendimento no banco.
do $$ declare t text; begin
  foreach t in array array['operacoes','usuario_operacoes','prioridades','naturezas_servico','tipos_servico','centros_custo','prestadores','prestador_documentos','ativos','ativo_arquivos','planos_manutencao','ordens_servico','ordens_servico_custos','ordem_servico_materiais','ordem_servico_arquivos','historico_ordens_servico','notificacoes']
  loop execute format('alter table public.%I enable row level security',t); end loop;
end $$;

create or replace function public.cw_pode_ver_os(p_id bigint) returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.ordens_servico o where o.id=p_id and public.cw_acesso_org(o.organizacao_id) and public.tem_permissao_usuario('os_visualizar_todas'));
$$;

create or replace function public.cw_resumo_os_solicitacao(p_solicitacao bigint)
returns table(id bigint,codigo text,titulo text,status text,inicio_previsto timestamptz,fim_previsto timestamptz)
language sql stable security definer set search_path=public as $$
  select o.id,o.codigo,o.titulo,o.status,o.inicio_previsto,o.fim_previsto from public.ordens_servico o
  join public.demandas d on d.id=o.solicitacao_id
  where d.id=p_solicitacao and public.cw_acesso_org(d.organizacao_id) and d.criado_por=auth.uid()
    and public.tem_permissao_usuario('os_visualizar_resumo') order by o.criado_em desc;
$$;

do $$ declare p record; begin
  for p in select schemaname,tablename,policyname from pg_policies where schemaname='public' and tablename in
    ('operacoes','usuario_operacoes','prioridades','naturezas_servico','tipos_servico','centros_custo','prestadores','prestador_documentos','ativos','ativo_arquivos','planos_manutencao','ordens_servico','ordens_servico_custos','ordem_servico_materiais','ordem_servico_arquivos','historico_ordens_servico','notificacoes')
  loop execute format('drop policy %I on %I.%I',p.policyname,p.schemaname,p.tablename); end loop;
end $$;

create policy cw_operacoes_select on public.operacoes for select to authenticated using(public.cw_acesso_org(organizacao_id));
create policy cw_operacoes_write on public.operacoes for all to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('configuracoes_editar')) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('configuracoes_editar'));
create policy cw_usuario_operacoes_select on public.usuario_operacoes for select to authenticated using(usuario_id=auth.uid() or exists(select 1 from public.operacoes o where o.id=operacao_id and public.cw_acesso_org(o.organizacao_id) and public.tem_permissao_usuario('usuarios_gerenciar')));
create policy cw_usuario_operacoes_write on public.usuario_operacoes for all to authenticated using(exists(select 1 from public.operacoes o where o.id=operacao_id and public.cw_acesso_org(o.organizacao_id) and public.tem_permissao_usuario('usuarios_gerenciar'))) with check(exists(select 1 from public.operacoes o where o.id=operacao_id and public.cw_acesso_org(o.organizacao_id) and public.tem_permissao_usuario('usuarios_gerenciar')));
create policy cw_prioridades_select on public.prioridades for select to authenticated using(public.cw_acesso_org(organizacao_id));
create policy cw_prioridades_write on public.prioridades for all to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('configuracoes_editar')) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('configuracoes_editar'));
create policy cw_naturezas_select on public.naturezas_servico for select to authenticated using(public.cw_acesso_org(organizacao_id));
create policy cw_naturezas_write on public.naturezas_servico for all to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('configuracoes_editar')) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('configuracoes_editar'));
create policy cw_tipos_select on public.tipos_servico for select to authenticated using(public.cw_acesso_org(organizacao_id));
create policy cw_tipos_write on public.tipos_servico for all to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('configuracoes_editar')) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('configuracoes_editar'));
create policy cw_centros_select on public.centros_custo for select to authenticated using(public.cw_acesso_org(organizacao_id));
create policy cw_centros_write on public.centros_custo for all to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('configuracoes_editar')) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('configuracoes_editar'));
create policy cw_prestadores_select on public.prestadores for select to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('prestadores_visualizar'));
create policy cw_prestadores_write on public.prestadores for all to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('prestadores_editar')) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('prestadores_editar'));
create policy cw_prestador_docs on public.prestador_documentos for all to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('prestadores_visualizar')) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('prestadores_editar'));
create policy cw_ativos_select on public.ativos for select to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('ativos_visualizar'));
create policy cw_ativos_write on public.ativos for all to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('ativos_editar')) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('ativos_editar'));
create policy cw_ativo_arquivos on public.ativo_arquivos for all to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('ativos_visualizar')) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('ativos_editar'));
create policy cw_planos_select on public.planos_manutencao for select to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('ativos_visualizar'));
create policy cw_planos_write on public.planos_manutencao for all to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('planos_editar')) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('planos_editar'));
create policy cw_os_select on public.ordens_servico for select to authenticated using(public.cw_pode_ver_os(id));
create policy cw_os_insert on public.ordens_servico for insert to authenticated with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('os_criar'));
create policy cw_os_update on public.ordens_servico for update to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('os_editar')) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('os_editar'));
create policy cw_os_custos on public.ordens_servico_custos for all to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('custos_visualizar')) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('custos_editar'));
create policy cw_os_materiais on public.ordem_servico_materiais for all to authenticated using(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('os_visualizar_todas')) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('os_editar'));
create policy cw_os_arquivos on public.ordem_servico_arquivos for all to authenticated using(public.cw_acesso_org(organizacao_id) and public.cw_pode_ver_os(ordem_servico_id)) with check(public.cw_acesso_org(organizacao_id) and public.tem_permissao_usuario('os_editar'));
create policy cw_os_historico on public.historico_ordens_servico for select to authenticated using(public.cw_acesso_org(organizacao_id) and public.cw_pode_ver_os(ordem_servico_id));
create policy cw_notificacoes_select on public.notificacoes for select to authenticated using(public.cw_acesso_org(organizacao_id) and (usuario_id is null or usuario_id=auth.uid()));
create policy cw_notificacoes_update on public.notificacoes for update to authenticated using(usuario_id=auth.uid()) with check(usuario_id=auth.uid());

-- Índices para paginação e filtros executados no banco.
create index if not exists demandas_org_tipo_data_idx on public.demandas(organizacao_id,tipo_demanda,criado_em desc,id desc);
create index if not exists demandas_org_status_data_idx on public.demandas(organizacao_id,status,criado_em desc,id desc);
create unique index if not exists demandas_org_codigo_sol_uidx on public.demandas(organizacao_id,codigo_solicitacao) where codigo_solicitacao is not null;
create index if not exists os_org_status_data_idx on public.ordens_servico(organizacao_id,status,criado_em desc,id desc);
create index if not exists os_solicitacao_idx on public.ordens_servico(solicitacao_id);
create index if not exists os_executor_idx on public.ordens_servico(organizacao_id,executor_id,status);
create index if not exists os_plano_data_idx on public.ordens_servico(plano_manutencao_id,inicio_previsto);
create index if not exists ativos_org_pai_idx on public.ativos(organizacao_id,ativo_pai_id,nome);
create index if not exists prestadores_org_ativo_idx on public.prestadores(organizacao_id,ativo,nome);
create index if not exists notificacoes_usuario_lida_idx on public.notificacoes(usuario_id,lida_em,criado_em desc);

-- Cadastros iniciais por empreendimento, sem substituir personalizações existentes.
insert into public.prioridades(organizacao_id,nome,ordem)
select o.id,v.nome,v.ordem from public.organizacoes o cross join (values('A definir',0),('Baixa',1),('Média',2),('Alta',3),('Urgente',4)) v(nome,ordem)
on conflict(organizacao_id,nome) do nothing;
insert into public.naturezas_servico(organizacao_id,nome)
select o.id,v.nome from public.organizacoes o cross join (values('Corretiva'),('Preventiva'),('Preditiva'),('Inspeção'),('Instalação'),('Adequação'),('Emergencial'),('Outro')) v(nome)
on conflict(organizacao_id,nome) do nothing;
insert into public.tipos_servico(organizacao_id,nome)
select o.id,v.nome from public.organizacoes o cross join (values('Elétrica'),('Hidráulica'),('Pintura'),('Civil'),('Impermeabilização'),('Climatização'),('Serralheria'),('Marcenaria'),('Segurança'),('Elevadores'),('Jardinagem'),('Limpeza'),('Outros')) v(nome)
on conflict(organizacao_id,nome) do nothing;

do $$ declare f record; begin
  for f in select oid::regprocedure assinatura from pg_proc where pronamespace='public'::regnamespace and proname like 'cw_%'
  loop execute format('revoke all on function %s from public,anon',f.assinatura); execute format('grant execute on function %s to authenticated',f.assinatura); end loop;
end $$;
grant select,insert,update,delete on public.operacoes,public.usuario_operacoes,public.prioridades,public.naturezas_servico,public.tipos_servico,public.centros_custo,public.prestadores,public.prestador_documentos,public.ativos,public.ativo_arquivos,public.planos_manutencao,public.ordens_servico,public.ordens_servico_custos,public.ordem_servico_materiais,public.ordem_servico_arquivos,public.historico_ordens_servico,public.notificacoes to authenticated;
grant usage,select on all sequences in schema public to authenticated;

insert into public.cw_migracoes(versao) values('arquitetura-v2') on conflict do nothing;
commit;
