-- CW Manutenção - anexos de imagens e vídeos
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'cw-anexos',
  'cw-anexos',
  false,
  52428800,
  array[
    'image/jpeg', 'image/png', 'image/webp', 'image/heic',
    'video/mp4', 'video/webm', 'video/quicktime'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.anexos_demandas (
  id bigint generated by default as identity primary key,
  demanda_id bigint not null references public.demandas(id) on delete cascade,
  storage_path text not null unique,
  nome_arquivo text not null,
  tipo_arquivo text not null,
  tamanho_bytes bigint,
  descricao text,
  criado_por uuid references auth.users(id),
  usuario_nome text,
  criado_em timestamptz not null default now()
);

create index if not exists anexos_demanda_idx
  on public.anexos_demandas (demanda_id, criado_em desc);

alter table public.anexos_demandas enable row level security;

create policy "usuario visualiza anexos da organizacao"
on public.anexos_demandas for select to authenticated
using (
  exists (
    select 1 from public.demandas d
    join public.perfis p on p.organizacao_id = d.organizacao_id
    where d.id = anexos_demandas.demanda_id and p.id = auth.uid()
  )
);

create policy "usuario adiciona anexos na organizacao"
on public.anexos_demandas for insert to authenticated
with check (
  criado_por = auth.uid() and exists (
    select 1 from public.demandas d
    join public.perfis p on p.organizacao_id = d.organizacao_id
    where d.id = anexos_demandas.demanda_id and p.id = auth.uid()
  )
);

create policy "usuario exclui os proprios anexos"
on public.anexos_demandas for delete to authenticated
using (criado_por = auth.uid());

create policy "usuario visualiza arquivos da organizacao"
on storage.objects for select to authenticated
using (
  bucket_id = 'cw-anexos' and exists (
    select 1 from public.demandas d
    join public.perfis p on p.organizacao_id = d.organizacao_id
    where d.id = ((storage.foldername(name))[1])::bigint and p.id = auth.uid()
  )
);

create policy "usuario envia arquivos para a organizacao"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'cw-anexos' and exists (
    select 1 from public.demandas d
    join public.perfis p on p.organizacao_id = d.organizacao_id
    where d.id = ((storage.foldername(name))[1])::bigint and p.id = auth.uid()
  )
);

create policy "usuario exclui os proprios arquivos"
on storage.objects for delete to authenticated
using (
  bucket_id = 'cw-anexos' and owner_id = auth.uid()::text
);
