-- CW Manutenção - estrutura inicial do banco
create extension if not exists pgcrypto;

create table if not exists public.organizacoes (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  criado_em timestamptz not null default now()
);

insert into public.organizacoes (nome)
select 'Serena Mall'
where not exists (select 1 from public.organizacoes where nome = 'Serena Mall');

create table if not exists public.perfis (
  id uuid primary key references auth.users(id) on delete cascade,
  organizacao_id uuid references public.organizacoes(id),
  nome text,
  papel text not null default 'administrador' check (papel in ('administrador','gestor','manutencao','solicitante')),
  criado_em timestamptz not null default now()
);

create table if not exists public.demandas (
  id bigint generated by default as identity primary key,
  organizacao_id uuid not null references public.organizacoes(id),
  titulo text not null,
  categoria text not null,
  local text not null,
  prioridade text not null default 'Média' check (prioridade in ('Baixa','Média','Alta','Urgente')),
  responsavel text,
  status text not null default 'A Fazer' check (status in ('A Fazer','Em Andamento','Aguardando Terceiros','Aguardando Aprovação','Concluída','Cancelada')),
  prazo date,
  proxima_acao text,
  observacoes text,
  criado_por uuid references auth.users(id),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  concluido_em timestamptz
);

create or replace function public.criar_perfil_usuario()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.perfis (id, organizacao_id, nome)
  values (new.id, (select id from public.organizacoes order by criado_em limit 1), coalesce(new.raw_user_meta_data->>'nome', split_part(new.email, '@', 1)));
  return new;
end;
$$;

drop trigger if exists ao_criar_usuario on auth.users;
create trigger ao_criar_usuario after insert on auth.users for each row execute procedure public.criar_perfil_usuario();

create or replace function public.atualizar_data_modificacao()
returns trigger language plpgsql as $$
begin new.atualizado_em = now(); return new; end;
$$;

drop trigger if exists atualizar_demanda on public.demandas;
create trigger atualizar_demanda before update on public.demandas for each row execute procedure public.atualizar_data_modificacao();

alter table public.organizacoes enable row level security;
alter table public.perfis enable row level security;
alter table public.demandas enable row level security;

create policy "usuario visualiza sua organizacao" on public.organizacoes for select to authenticated
using (id = (select organizacao_id from public.perfis where id = auth.uid()));

create policy "usuario visualiza o proprio perfil" on public.perfis for select to authenticated
using (id = auth.uid());

create policy "usuario atualiza o proprio perfil" on public.perfis for update to authenticated
using (id = auth.uid()) with check (id = auth.uid());

create policy "usuario visualiza demandas da organizacao" on public.demandas for select to authenticated
using (organizacao_id = (select organizacao_id from public.perfis where id = auth.uid()));

create policy "usuario cria demanda na organizacao" on public.demandas for insert to authenticated
with check (organizacao_id = (select organizacao_id from public.perfis where id = auth.uid()) and criado_por = auth.uid());

create policy "usuario atualiza demandas da organizacao" on public.demandas for update to authenticated
using (organizacao_id = (select organizacao_id from public.perfis where id = auth.uid()))
with check (organizacao_id = (select organizacao_id from public.perfis where id = auth.uid()));

create index if not exists demandas_organizacao_idx on public.demandas (organizacao_id);
create index if not exists demandas_status_idx on public.demandas (status);
create index if not exists demandas_prazo_idx on public.demandas (prazo);
