const SUPABASE_URL='https://qtxkasllovxjzukmxuav.supabase.co';
const SUPABASE_KEY='sb_publishable_gZSpBs9S4ahLFCwJaESYxA_37nSh-yC';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const STATUS=['A Fazer','Em Andamento','Aguardando Terceiros','Aguardando Aprovação','Concluída','Cancelada'];
const PRIORITIES=['Não classificada','Baixa','Média','Alta','Urgente'];
const CATEGORIES=['Manutenção','Obra','Elétrica','Hidráulica','Climatização','Civil','Segurança','Orçamento','Administrativo'];
const RESPONSIBLES=['Welber','Leandro','Fornecedor','Direção','Outro'];
let demands=[],profile=null,session=null,signupMode=false,editingId=null,permissions={};
const el=id=>document.getElementById(id);
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,'-');
const fmt=s=>s?new Intl.DateTimeFormat('pt-BR').format(new Date(s+'T12:00:00')):'—';
const open=d=>!['Concluída','Cancelada'].includes(d.status);
const today=()=>new Date().toISOString().slice(0,10);
const late=d=>open(d)&&d.deadline&&d.deadline<today();
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const badge=(x,t)=>`<span class="badge ${t}-${slug(x)}">${x}</span>`;
const role=()=>String(profile?.papel||'').toLowerCase();
const hasPermission=action=>role()==='administrador'||permissions[action]===true;
const canManage=()=>hasPermission('gerenciar_usuarios');
const isAdmin=()=>role()==='administrador';
const isStore=()=>role()==='lojista';
const canEditDemand=d=>!!d&&(hasPermission('editar_todas')||(hasPermission('editar_proprias')&&d.criado_por===session?.user?.id));
const ROLE_LABELS={administrador:'Administrador',gestor_manutencao:'Gestor Manut.',tecnico:'Técnico',lojista:'Lojista'};
function applyRoleVisibility(){const form=el('form'),showField=(name,show)=>{const field=form?.elements[name]?.closest('.field');if(field)field.style.display=show?'':'none'};showField('category',hasPermission('alterar_status'));showField('priority',hasPermission('classificar_prioridade'));['responsible','status','deadline','next'].forEach(name=>showField(name,hasPermission('alterar_status')));document.querySelectorAll('[data-new]').forEach(x=>x.style.display=hasPermission('cadastrar_demanda')?'':'none');const newNav=document.querySelector('.nav[data-view="nova"]');if(newNav)newNav.style.display=hasPermission('cadastrar_demanda')?'':'none';const usersNav=el('usersNav');if(usersNav)usersNav.style.display=canManage()?'':'none'}

function toast(msg){const t=el('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function show(name){const labels={dashboard:['Visão geral','Acompanhe as demandas de manutenção'],demandas:['Demandas','Consulte e filtre todos os registros'],detalhes:['Detalhes da demanda','Consulte todas as informações'],nova:['Nova demanda','Cadastre uma solicitação de manutenção']};document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));el(name).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===name));el('title').textContent=labels[name][0];el('subtitle').textContent=labels[name][1];el('sidebar').classList.remove('open')}
const showBase=show;
show=function(name){if(name!=='usuarios'){showBase(name);return}if(!canManage()){toast('Acesso restrito.');return}document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));el('usuarios').classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===name));el('title').textContent='Usuários';el('subtitle').textContent='Gerencie perfis, lojas e acessos';el('sidebar').classList.remove('open');loadUsers()}
async function loadUsers(){if(!canManage())return;el('usersList').innerHTML='<p class="muted">Carregando usuários...</p>';const {data,error}=await db.from('perfis').select('*').order('nome');if(error){el('usersList').innerHTML='<p class="muted">Não foi possível carregar os usuários.</p>';return}el('usersList').innerHTML=`<div style="overflow:auto"><table class="table"><thead><tr><th>Usuário</th><th>Loja/local</th><th>Perfil</th><th>Acesso</th><th></th></tr></thead><tbody>${(data||[]).map(u=>`<tr><td><strong>${esc(u.nome||'Sem nome')}</strong>${u.id===session.user.id?'<small class="muted" style="display:block">Você</small>':''}</td><td><input id="store-${u.id}" value="${esc(u.loja||'')}" placeholder="Nome da loja" style="min-width:160px"></td><td><select id="role-${u.id}" style="min-width:150px">${Object.entries(ROLE_LABELS).map(([value,label])=>`<option value="${value}" ${u.papel===value?'selected':''}>${label}</option>`).join('')}</select></td><td><select id="active-${u.id}"><option value="true" ${u.ativo!==false?'selected':''}>Ativo</option><option value="false" ${u.ativo===false?'selected':''}>Bloqueado</option></select></td><td><button class="edit-button" onclick="saveUserProfile('${u.id}')">Salvar</button></td></tr>`).join('')}</tbody></table></div>`}
async function saveUserProfile(id){if(!canManage())return;const papel=el(`role-${id}`).value,loja=el(`store-${id}`).value.trim(),ativo=el(`active-${id}`).value==='true';if(id===session.user.id&&(!ativo||!['administrador','gestor_manutencao'].includes(papel))&&!confirm('Esta alteração pode retirar seu acesso à gestão. Deseja continuar?'))return;const {error}=await db.from('perfis').update({papel,loja:loja||null,ativo}).eq('id',id);if(error){toast('Não foi possível atualizar: '+error.message);return}toast('Usuário atualizado.');if(id===session.user.id)await loadProfile();await loadUsers()}
const loadUsersBasic=loadUsers;
loadUsers=async function(){if(!canManage())return;el('usersList').innerHTML='<p class="muted">Carregando usuários...</p>';const {data,error}=await db.from('perfis').select('*').order('nome');if(error){el('usersList').innerHTML='<p class="muted">Não foi possível carregar os usuários.</p>';return}el('usersList').innerHTML=`<div style="overflow:auto"><table class="table"><thead><tr><th>Usuário</th><th>Loja/local</th><th>Perfil</th><th>Acesso</th><th>Ações</th></tr></thead><tbody>${(data||[]).map(u=>`<tr><td><strong>${esc(u.nome||'Sem nome')}</strong><small class="muted" style="display:block">${esc(u.email||'')}</small></td><td><input id="store-${u.id}" value="${esc(u.loja||'')}" placeholder="Nome da loja"></td><td><select id="role-${u.id}">${Object.entries(ROLE_LABELS).map(([value,label])=>`<option value="${value}" ${u.papel===value?'selected':''}>${label}</option>`).join('')}</select></td><td><select id="active-${u.id}"><option value="true" ${u.ativo!==false?'selected':''}>Ativo</option><option value="false" ${u.ativo===false?'selected':''}>Bloqueado</option></select></td><td style="white-space:nowrap"><button class="edit-button" onclick="saveUserProfile('${u.id}')">Salvar</button> <button class="link" onclick="sendPasswordReset('${esc(u.email||'')}')">Redefinir senha</button></td></tr>`).join('')}</tbody></table></div>`;if(isAdmin())loadPermissionMatrix()}
async function createManagedUser(e){e.preventDefault();const f=e.target,button=el('createUserButton');button.disabled=true;try{const {data,error}=await db.functions.invoke('admin-users',{body:{action:'create',nome:f.nome.value.trim(),email:f.email.value.trim(),password:f.password.value,papel:f.papel.value,loja:f.loja.value.trim()}});if(error||data?.error)throw new Error(data?.error||error.message);f.reset();toast('Usuário criado com sucesso.');await loadUsers()}catch(error){toast('Não foi possível criar: '+error.message)}finally{button.disabled=false}}
async function sendPasswordReset(email){if(!email){toast('Este usuário ainda não possui e-mail registrado.');return}if(!confirm(`Enviar redefinição de senha para ${email}?`))return;const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});toast(error?'Não foi possível enviar: '+error.message:'E-mail de redefinição enviado.')}
const PERMISSION_LABELS={visualizar_todas:'Visualizar todas as demandas',visualizar_proprias:'Visualizar somente as próprias',cadastrar_demanda:'Cadastrar demanda',editar_todas:'Editar qualquer demanda',editar_proprias:'Editar as próprias demandas',classificar_prioridade:'Classificar prioridade',alterar_status:'Alterar status, responsável e prazo',excluir_midia:'Excluir mídia',apagar_demanda:'Apagar demanda',visualizar_historico:'Visualizar histórico',gerenciar_usuarios:'Gerenciar usuários',gerenciar_permissoes:'Gerenciar permissões'};
async function loadPermissionMatrix(){const {data,error}=await db.from('permissoes_perfis').select('*').eq('organizacao_id',profile.organizacao_id);if(error)return;const map={};(data||[]).forEach(x=>map[`${x.papel}:${x.acao}`]=x.permitido);const roles=['administrador','gestor_manutencao','tecnico','lojista'];el('permissionMatrix').innerHTML=`<div style="overflow:auto"><table class="table"><thead><tr><th>Ação</th>${roles.map(r=>`<th>${ROLE_LABELS[r]}</th>`).join('')}</tr></thead><tbody>${Object.entries(PERMISSION_LABELS).map(([action,label])=>`<tr><td>${label}</td>${roles.map(r=>`<td style="text-align:center"><input type="checkbox" ${r==='administrador'||map[`${r}:${action}`]?'checked':''} ${r==='administrador'?'disabled':''} onchange="savePermission('${r}','${action}',this.checked)"></td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
async function savePermission(papel,acao,permitido){if(!isAdmin())return;const {error}=await db.from('permissoes_perfis').upsert({organizacao_id:profile.organizacao_id,papel,acao,permitido,atualizado_em:new Date().toISOString()});toast(error?'Não foi possível alterar a permissão.':'Permissão atualizada.')}
function metrics(){const m=[['Demandas abertas',demands.filter(open).length,'☷',''],['Em atraso',demands.filter(late).length,'!','danger'],['Aguardando retorno',demands.filter(d=>d.status.includes('Aguardando')).length,'◷','wait'],['Concluídas',demands.filter(d=>d.status==='Concluída').length,'✓','done']];el('metrics').innerHTML=m.map(x=>`<article class="card ${x[3]}"><div class="card-top"><span>${x[0]}</span><span class="icon">${x[2]}</span></div><div class="value">${x[1]}</div></article>`).join('')}
function charts(){const colors=['#94a3b8','#2563eb','#e59b23','#8b5cf6','#16865d','#64748b'],counts=STATUS.map(s=>demands.filter(d=>d.status===s).length),max=Math.max(...counts,1);el('statusChart').innerHTML=STATUS.map((s,i)=>`<div class="chart-row"><span>${s}</span><div class="track"><div class="bar" style="width:${counts[i]/max*100}%;background:${colors[i]}"></div></div><b>${counts[i]}</b></div>`).join('');el('priorities').innerHTML=PRIORITIES.map(p=>`<div class="priority-row">${badge(p,'priority')}<b>${demands.filter(d=>open(d)&&d.priority===p).length}</b></div>`).join('')}
function table(items){if(!items.length)return'<div class="empty">Nenhuma demanda encontrada.</div>';return `<div style="overflow:auto"><table class="table"><thead><tr><th>Demanda</th><th>Local</th><th>Responsável</th><th>Prazo</th><th>Prioridade</th><th>Status</th><th>Ações</th></tr></thead><tbody>${items.map(d=>`<tr><td><span class="d-title">${esc(d.title)}</span><span class="muted">${d.category}</span></td><td>${esc(d.location)}</td><td>${esc(d.responsible||'—')}</td><td class="${late(d)?'late':''}">${fmt(d.deadline)}</td><td>${badge(d.priority,'priority')}</td><td>${badge(d.status,'status')}</td><td><button class="edit-button" onclick="viewDemand(${d.id})">Visualizar</button></td></tr>`).join('')}</tbody></table></div>`}
function lists(){el('recent').innerHTML=table(demands.slice(0,5));const q=el('search').value.toLowerCase(),s=el('filterStatus').value,p=el('filterPriority').value;el('list').innerHTML=table(demands.filter(d=>(!q||[d.title,d.location,d.responsible,d.category].join(' ').toLowerCase().includes(q))&&(!s||d.status===s)&&(!p||d.priority===p)))}
function render(){metrics();charts();lists()}
function cancelEdit(){editingId=null;el('form').reset();el('saveDemand').textContent='Cadastrar demanda';el('cancelEdit').style.display='none';el('historyPanel').style.display='none';el('historyList').innerHTML='';el('attachmentsPanel').style.display='none';el('attachmentsList').innerHTML='';el('attachmentFiles').value='';el('attachmentDescription').value='';el('uploadStatus').textContent='';document.querySelector('#nova .heading h2').textContent='Cadastrar demanda';document.querySelector('#nova .heading p').textContent='Registre uma nova solicitação'}
async function loadHistory(id){el('historyPanel').style.display='block';el('historyList').innerHTML='<p class="muted">Carregando histórico...</p>';const {data,error}=await db.from('historico_demandas').select('*').eq('demanda_id',id).order('criado_em',{ascending:false});if(error){el('historyList').innerHTML='<p class="muted">Não foi possível carregar o histórico.</p>';return}if(!data?.length){el('historyList').innerHTML='<p class="muted">Nenhuma alteração registrada até o momento.</p>';return}el('historyList').innerHTML=data.map(item=>{const changes=Object.entries(item.alteracoes||{}).map(([field,value])=>`<div style="margin-top:8px"><strong>${esc(field)}:</strong> <span class="muted">${esc(value.anterior??'Vazio')}</span> → <strong>${esc(value.novo??'Vazio')}</strong></div>`).join('');return `<article style="padding:16px 0;border-bottom:1px solid #edf0f4"><div style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap"><strong>${esc(item.usuario_nome||'Usuário')}</strong><span class="muted">${new Date(item.criado_em).toLocaleString('pt-BR')}</span></div>${changes}</article>`}).join('')}
async function loadAttachments(id){el('attachmentsPanel').style.display='block';el('attachmentsList').innerHTML='<p class="muted">Carregando anexos...</p>';const {data,error}=await db.from('anexos_demandas').select('*').eq('demanda_id',id).order('criado_em',{ascending:false});if(error){el('attachmentsList').innerHTML='<p class="muted">Não foi possível carregar os anexos.</p>';return}if(!data?.length){el('attachmentsList').innerHTML='<p class="muted">Nenhum anexo adicionado.</p>';return}const cards=await Promise.all(data.map(async item=>{const {data:signed}=await db.storage.from('cw-anexos').createSignedUrl(item.storage_path,3600);const url=signed?.signedUrl||'';let media=item.tipo_arquivo.startsWith('image/')?`<img src="${url}" alt="${esc(item.descricao||item.nome_arquivo)}" style="width:100%;height:160px;object-fit:cover;border-radius:9px;background:#eef1f5">`:item.tipo_arquivo.startsWith('video/')?`<video src="${url}" controls preload="metadata" style="width:100%;height:160px;border-radius:9px;background:#111"></video>`:`<a href="${url}" target="_blank">Abrir arquivo</a>`;const remove=item.criado_por===session.user.id?`<button class="link" onclick="deleteAttachment(${item.id},'${esc(item.storage_path)}')">Excluir</button>`:'';return `<article style="border:1px solid #e3e8ef;border-radius:12px;padding:10px;background:#fff">${media}<div style="padding:10px 3px 3px"><strong style="display:block;overflow:hidden;text-overflow:ellipsis">${esc(item.nome_arquivo)}</strong><p style="margin:7px 0">${esc(item.descricao||'Sem descrição')}</p><small class="muted">${esc(item.usuario_nome||'Usuário')} • ${new Date(item.criado_em).toLocaleString('pt-BR')}</small><div style="margin-top:8px">${remove}</div></div></article>`}));el('attachmentsList').innerHTML=cards.join('')}
async function deleteAttachment(id,path){if(!confirm('Excluir esta mídia? Esta ação não poderá ser desfeita.'))return;const {error:fileError}=await db.storage.from('cw-anexos').remove([path]);if(fileError){toast('Não foi possível excluir o arquivo.');return}const {error}=await db.from('anexos_demandas').delete().eq('id',id);if(error){toast('Arquivo excluído, mas o registro não foi removido.');return}toast('Mídia excluída.');await Promise.all([loadGallery(editingId,'detailsAttachments'),loadGallery(editingId,'attachmentsList'),loadHistoryInto(editingId,'detailsHistory'),loadHistory(editingId)])}
async function loadGallery(id,target){el(target).innerHTML='<p class="muted">Carregando anexos...</p>';const {data,error}=await db.from('anexos_demandas').select('*').eq('demanda_id',id).order('criado_em',{ascending:false});if(error||!data?.length){el(target).innerHTML='<p class="muted">Nenhum anexo adicionado.</p>';return}const cards=await Promise.all(data.map(async item=>{const {data:signed}=await db.storage.from('cw-anexos').createSignedUrl(item.storage_path,3600),url=signed?.signedUrl||'',encoded=encodeURIComponent(url),title=encodeURIComponent(item.nome_arquivo),isImage=item.tipo_arquivo.startsWith('image/'),preview=isImage?`<img src="${url}" alt="${esc(item.nome_arquivo)}" style="width:100%;height:170px;object-fit:cover;border-radius:9px">`:`<video src="${url}" preload="metadata" style="width:100%;height:170px;object-fit:cover;border-radius:9px;background:#111"></video>`,remove=target==='attachmentsList'&&item.criado_por===session.user.id?`<button type="button" class="link" onclick="deleteAttachment(${item.id},'${esc(item.storage_path)}')" style="color:#b42318;padding:7px 2px">Excluir mídia</button>`:'';return `<article style="border:1px solid #e3e8ef;border-radius:12px;padding:10px;background:#fff"><button type="button" onclick="openMedia('${encoded}','${item.tipo_arquivo}','${title}')" style="border:0;padding:0;background:transparent;width:100%;text-align:left;cursor:pointer">${preview}<strong style="display:block;padding:9px 2px 3px;overflow:hidden;text-overflow:ellipsis">${esc(item.nome_arquivo)}</strong><small class="muted">${new Date(item.criado_em).toLocaleString('pt-BR')}</small></button><div style="margin-top:5px">${remove}</div></article>`}));el(target).innerHTML=cards.join('')}
function openMedia(encoded,type,title){const url=decodeURIComponent(encoded),name=decodeURIComponent(title);el('mediaContent').innerHTML=type.startsWith('image/')?`<img src="${url}" alt="${esc(name)}" style="max-width:100%;max-height:88vh;object-fit:contain">`:`<video src="${url}" controls autoplay style="max-width:100%;max-height:88vh"></video>`;el('mediaModal').style.display='flex'}
const renderGallery=loadGallery;
loadGallery=async function(id,target){await renderGallery(id,target);const demand=demands.find(item=>Number(item.id)===Number(id));if(target==='detailsAttachments')el('editFromDetails').style.display=canEditDemand(demand)?'':'none';if(!hasPermission('excluir_midia')){el(target).querySelectorAll('[onclick^="deleteAttachment"]').forEach(x=>x.remove());return}if(target!=='attachmentsList')return;const {data}=await db.from('anexos_demandas').select('id,storage_path').eq('demanda_id',id).order('criado_em',{ascending:false});[...el(target).querySelectorAll('article')].forEach((card,index)=>{if(card.querySelector('[onclick^="deleteAttachment"]')||!data?.[index])return;const item=data[index],actions=card.lastElementChild;actions.insertAdjacentHTML('beforeend',`<button type="button" class="link" onclick="deleteAttachment(${item.id},'${esc(item.storage_path)}')" style="color:#b42318;padding:7px 2px">Excluir mídia</button>`)})}
async function loadHistoryInto(id,target){el(target).innerHTML='<p class="muted">Carregando histórico...</p>';const {data,error}=await db.from('historico_demandas').select('*').eq('demanda_id',id).order('criado_em',{ascending:false});if(error||!data?.length){el(target).innerHTML='<p class="muted">Nenhuma alteração registrada.</p>';return}el(target).innerHTML=data.map(item=>{const changes=Object.entries(item.alteracoes||{}).map(([field,value])=>`<div style="margin-top:7px"><strong>${esc(field)}:</strong> ${esc(value.anterior??'Vazio')} → ${esc(value.novo??'Vazio')}</div>`).join('');return `<article style="padding:14px 0;border-bottom:1px solid #edf0f4"><strong>${esc(item.usuario_nome||'Usuário')}</strong><span class="muted" style="float:right">${new Date(item.criado_em).toLocaleString('pt-BR')}</span>${changes}</article>`}).join('')}
function viewDemand(id){const d=demands.find(item=>Number(item.id)===Number(id));if(!d)return;editingId=d.id;const nextAction=canManage()?`<div style="grid-column:1/-1"><small class="muted">Próxima ação</small><p>${esc(d.next||'Não informada')}</p></div>`:'';el('detailsContent').innerHTML=`<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:16px"><div><small class="muted">Título</small><strong style="display:block;margin-top:5px">${esc(d.title)}</strong></div><div><small class="muted">Data do cadastro</small><strong style="display:block;margin-top:5px">${new Date(d.createdAt).toLocaleString('pt-BR')}</strong></div><div><small class="muted">Local</small><strong style="display:block;margin-top:5px">${esc(d.location)}</strong></div><div><small class="muted">Categoria</small><strong style="display:block;margin-top:5px">${esc(d.category)}</strong></div><div><small class="muted">Prioridade</small><div style="margin-top:5px">${badge(d.priority,'priority')}</div></div><div><small class="muted">Status</small><div style="margin-top:5px">${badge(d.status,'status')}</div></div><div><small class="muted">Responsável</small><strong style="display:block;margin-top:5px">${esc(d.responsible||'—')}</strong></div><div><small class="muted">Prazo</small><strong style="display:block;margin-top:5px">${fmt(d.deadline)}</strong></div><div style="grid-column:1/-1"><small class="muted">Descrição do problema</small><p style="white-space:pre-wrap;line-height:1.6">${esc(d.notes||'Sem descrição')}</p></div>${nextAction}</div>`;show('detalhes');loadGallery(d.id,'detailsAttachments');loadHistoryInto(d.id,'detailsHistory')}
function startEdit(id){const d=demands.find(item=>Number(item.id)===Number(id));if(!d)return;editingId=d.id;const f=el('form').elements;f.title.value=d.title||'';f.category.value=d.category||'Manutenção';f.location.value=d.location||'';f.priority.value=d.priority||'Média';f.responsible.value=d.responsible||'Outro';f.status.value=d.status||'A Fazer';f.deadline.value=d.deadline||'';f.next.value=d.next||'';f.notes.value=d.notes||'';el('saveDemand').textContent='Salvar alterações';el('cancelEdit').style.display='inline-block';document.querySelector('#nova .heading h2').textContent='Editar demanda';document.querySelector('#nova .heading p').textContent='Atualize as informações e o andamento';show('nova');el('attachmentsPanel').style.display='block';loadGallery(d.id,'attachmentsList');loadHistory(d.id)}
async function loadData(){const {data,error}=await db.from('demandas').select('*').order('criado_em',{ascending:false});if(error){toast('Não foi possível carregar as demandas.');return}demands=(data||[]).map(d=>({...d,title:d.titulo,category:d.categoria,location:d.local,priority:d.prioridade,deadline:d.prazo,responsible:d.responsavel,next:d.proxima_acao,notes:d.observacoes,createdAt:d.criado_em}));render()}
async function loadProfile(){const {data,error}=await db.from('perfis').select('*').eq('id',session.user.id).maybeSingle();if(error)throw error;profile=data;if(data?.ativo===false){await db.auth.signOut();throw new Error('Seu acesso está bloqueado.')}permissions={};if(data?.papel!=='administrador'){const {data:rules}=await db.from('permissoes_perfis').select('acao,permitido').eq('organizacao_id',data.organizacao_id).eq('papel',data.papel);(rules||[]).forEach(item=>permissions[item.acao]=item.permitido)}const name=data?.nome||session.user.email;el('userName').textContent=name;el('userRole').textContent=ROLE_LABELS[data?.papel]||'Usuário';el('userInitials').textContent=name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();applyRoleVisibility();return profile}
async function migrateLocalDemands(){if(localStorage.getItem('cw-migrated-v1')||!profile?.organizacao_id)return;let local=[];try{local=JSON.parse(localStorage.getItem('cw-demands')||'[]')}catch{}const created=local.filter(d=>Number(d.id)>1000000000000);if(!created.length){localStorage.setItem('cw-migrated-v1','done');return}const rows=created.map(d=>({organizacao_id:profile.organizacao_id,titulo:d.title,categoria:d.category,local:d.location,prioridade:d.priority||'Média',responsavel:d.responsible||null,status:d.status||'A Fazer',prazo:d.deadline||null,proxima_acao:d.next||null,observacoes:d.notes||null,criado_por:session.user.id}));const {error}=await db.from('demandas').insert(rows);if(!error){localStorage.setItem('cw-migrated-v1','done');toast(`${rows.length} demanda(s) antiga(s) recuperada(s).`)}}
async function enterApp(current){session=current;el('authScreen').classList.toggle('hidden',!!session);if(session){await loadProfile();await migrateLocalDemands();await loadData()}else{demands=[];render()}}

el('form').className='demand-form';
el('form').innerHTML=`<div class="field full"><label>Título da demanda *</label><input name="title" required placeholder="Ex.: Reparo na iluminação"></div><div class="field"><label>Categoria *</label><select name="category">${CATEGORIES.map(x=>`<option>${x}</option>`)}</select></div><div class="field"><label>Local *</label><input name="location" required placeholder="Ex.: 3º piso"></div><div class="field"><label>Prioridade *</label><select name="priority">${PRIORITIES.map(x=>`<option ${x==='Média'?'selected':''}>${x}</option>`)}</select></div><div class="field"><label>Responsável</label><select name="responsible">${RESPONSIBLES.map(x=>`<option>${x}</option>`)}</select></div><div class="field"><label>Status *</label><select name="status">${STATUS.map(x=>`<option>${x}</option>`)}</select></div><div class="field"><label>Prazo previsto</label><input name="deadline" type="date"></div><div class="field full"><label>Descrição do problema *</label><textarea name="notes" required placeholder="Descreva o problema, sintomas e informações importantes"></textarea></div><div id="nextActionField" class="field full"><label>Dependência / próxima ação</label><input name="next" placeholder="Informe o próximo passo"></div><div class="field full"><label>Imagens e vídeos</label><input id="newDemandFiles" type="file" accept="image/jpeg,image/png,image/webp,image/heic,video/mp4,video/webm,video/quicktime" multiple><small class="muted">Até 50 MB por arquivo.</small></div><div class="actions"><button id="cancelEdit" type="button" class="secondary" style="display:none">Cancelar edição</button><button type="reset" class="secondary">Limpar</button><button id="saveDemand" type="submit" class="primary">Cadastrar demanda</button></div>`;
applyRoleVisibility();
el('filterStatus').innerHTML+=STATUS.map(x=>`<option>${x}</option>`).join('');
el('filterPriority').innerHTML+=PRIORITIES.map(x=>`<option>${x}</option>`).join('');
document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>show(x.dataset.view));
document.querySelectorAll('[data-new]').forEach(x=>x.onclick=()=>{cancelEdit();show('nova')});
document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>show(x.dataset.go));
el('menu').onclick=()=>el('sidebar').classList.toggle('open');
['search','filterStatus','filterPriority'].forEach(id=>el(id).addEventListener(id==='search'?'input':'change',lists));
async function uploadDemandFiles(demandId,files){for(const file of files){if(file.size>52428800)throw new Error(`${file.name} ultrapassa 50 MB.`);const safe=file.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'-'),path=`${demandId}/${crypto.randomUUID()}-${safe}`;const {error:uploadError}=await db.storage.from('cw-anexos').upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {error:recordError}=await db.from('anexos_demandas').insert({demanda_id:demandId,storage_path:path,nome_arquivo:file.name,tipo_arquivo:file.type,tamanho_bytes:file.size,descricao:null,criado_por:session.user.id,usuario_nome:profile?.nome||session.user.email});if(recordError){await db.storage.from('cw-anexos').remove([path]);throw recordError}}}
el('form').onsubmit=async e=>{e.preventDefault();const button=el('saveDemand'),isEditing=editingId!==null,files=[...el('newDemandFiles').files];if(button.disabled)return;button.disabled=true;button.textContent=files.length?'Salvando e enviando arquivos...':'Salvando...';try{if(!session)throw new Error('Sua sessão expirou. Entre novamente.');if(!profile)await loadProfile();if(role()==='tecnico')throw new Error('O perfil Técnico possui acesso somente para visualização.');if(!profile?.organizacao_id)throw new Error('Seu perfil ainda não está vinculado ao Serena Mall.');const x=Object.fromEntries(new FormData(e.target)),store=isStore();const payload={organizacao_id:profile.organizacao_id,titulo:x.title.trim(),categoria:store?'Manutenção':x.category,local:x.location.trim(),prioridade:store?'Não classificada':x.priority,responsavel:store?null:x.responsible,status:store?'A Fazer':x.status,prazo:store?null:(x.deadline||null),proxima_acao:store?null:x.next.trim(),observacoes:x.notes.trim()};const result=!isEditing&&store?await db.rpc('criar_demanda_lojista',{p_titulo:payload.titulo,p_local:payload.local,p_observacoes:payload.observacoes}):await (isEditing?db.from('demandas').update(payload).eq('id',editingId):db.from('demandas').insert({...payload,criado_por:session.user.id})).select('id').single();const {data,error}=result;if(error)throw error;if(!data)throw new Error('O Supabase não confirmou a operação.');const savedId=data.id;let mediaError=null;if(files.length){try{await uploadDemandFiles(savedId,files)}catch(error){mediaError=error}}cancelEdit();await loadData();viewDemand(savedId);toast(mediaError?'Demanda salva, mas alguns arquivos falharam: '+mediaError.message:(isEditing?'Demanda atualizada com sucesso.':'Demanda cadastrada com sucesso.'))}catch(error){console.error(error);toast('Não foi possível salvar: '+(error.message||'tente novamente.'))}finally{button.disabled=false;if(editingId!==null)button.textContent='Salvar alterações'}}
el('cancelEdit').onclick=()=>{cancelEdit();show('demandas')};
el('editFromDetails').onclick=()=>{const demand=demands.find(item=>Number(item.id)===Number(editingId));if(!canEditDemand(demand)){toast('Somente o criador da demanda ou um administrador pode editar.');return}startEdit(editingId)};
el('closeMedia').onclick=()=>{el('mediaModal').style.display='none';el('mediaContent').innerHTML=''};
el('mediaModal').onclick=e=>{if(e.target===el('mediaModal'))el('closeMedia').click()};
el('uploadAttachments').onclick=async()=>{const files=[...el('attachmentFiles').files],description=el('attachmentDescription').value.trim(),button=el('uploadAttachments');if(!editingId)return;if(!files.length){toast('Selecione pelo menos um arquivo.');return}button.disabled=true;el('uploadStatus').textContent=`Enviando 0 de ${files.length}...`;let completed=0;try{for(const file of files){if(file.size>52428800)throw new Error(`${file.name} ultrapassa 50 MB.`);const safe=file.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]/g,'-'),path=`${editingId}/${crypto.randomUUID()}-${safe}`;const {error:uploadError}=await db.storage.from('cw-anexos').upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {error:recordError}=await db.from('anexos_demandas').insert({demanda_id:editingId,storage_path:path,nome_arquivo:file.name,tipo_arquivo:file.type,tamanho_bytes:file.size,descricao:description||null,criado_por:session.user.id,usuario_nome:profile?.nome||session.user.email});if(recordError){await db.storage.from('cw-anexos').remove([path]);throw recordError}completed++;el('uploadStatus').textContent=`Enviando ${completed} de ${files.length}...`}el('attachmentFiles').value='';el('attachmentDescription').value='';el('uploadStatus').textContent='Envio concluído.';toast('Anexos enviados com sucesso.');await loadAttachments(editingId)}catch(error){console.error(error);el('uploadStatus').textContent='Falha no envio.';toast('Não foi possível enviar: '+error.message)}finally{button.disabled=false}};
el('toggleAuth').onclick=()=>{signupMode=!signupMode;el('nameField').classList.toggle('visible',signupMode);el('toggleAuth').textContent=signupMode?'Já tenho cadastro':'Ainda não tenho cadastro';document.querySelector('.auth-submit').textContent=signupMode?'Criar conta':'Entrar';el('authMessage').textContent=''}
el('authForm').onsubmit=async e=>{e.preventDefault();el('authMessage').textContent='Aguarde...';const email=el('authEmail').value,password=el('authPassword').value,name=el('authName').value;const result=signupMode?await db.auth.signUp({email,password,options:{data:{nome:name}}}):await db.auth.signInWithPassword({email,password});if(result.error){el('authMessage').textContent=result.error.message;return}if(signupMode&&!result.data.session){el('authMessage').textContent='Confira seu e-mail para confirmar o cadastro.';return}el('authMessage').textContent=''}
el('logout').onclick=()=>db.auth.signOut();
db.auth.onAuthStateChange((_event,current)=>setTimeout(()=>enterApp(current),0));
db.auth.getSession().then(({data})=>enterApp(data.session));
render();
