import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useFieldArray, useForm } from 'react-hook-form'
import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { z } from 'zod'
import { useAuthorization } from '@/app/authorization/use-authorization'
import { useAuth } from '@/app/auth/use-auth'
import { useCadastroGateways } from '@/app/cadastros/cadastro-gateways-context'
import { CadastroContentState } from '@/app/pages/cadastros/cadastro-content-state'
import { CadastroPageHeader } from '@/app/pages/cadastros/cadastro-page-header'
import { tenantQueryKey } from '@/app/query/tenant-query-key'
import { canonicalTenantPath } from '@/app/router/tenant-route'
import { normalizeAppError } from '@/shared/errors/app-error'
import {
  checklistResponseTypeSchema,
  maintenanceReasonContextSchema,
  type ChecklistTemplate,
  type ChecklistTemplateListItem,
  type MaintenanceCatalogCommandResult,
  type MaintenanceCatalogStatus,
  type MaintenanceCategoryLookup,
  type MaintenanceReasonContext,
} from '@/shared/maintenance-catalogs/maintenance-catalogs'
import { Button } from '@/shared/ui/button'
import { StatePanel } from '@/shared/ui/state-panel'

const optionalUuid = z.union([z.literal(''), z.string().uuid('Selecione uma opção válida.')])
const catalogFormSchema = z.object({ code: z.string().trim().max(64), name: z.string().trim().min(1, 'Informe um nome.').max(160), description: z.string().trim().max(2_000), reason: z.string().trim().min(1, 'Informe o motivo.').max(500), categoryId: optionalUuid, usageContext: z.union([z.literal(''), maintenanceReasonContextSchema]) })
type CatalogFormValue = z.infer<typeof catalogFormSchema>
interface CatalogRow { id: string; code: string | null; name: string; description: string | null; status: MaintenanceCatalogStatus; version: number; category_id?: string; usage_context?: MaintenanceReasonContext }

function context(reason: string, prefix: string) { const id = globalThis.crypto.randomUUID(); return { reason, correlationId: id, idempotencyKey: `${prefix}-${id}` } }
function safeError(error: unknown) { return normalizeAppError(error).message }
function useKey(resource: string, filters?: Record<string, unknown>) { const { state } = useAuthorization(); if (state.status !== 'ready') throw new Error('Authorization projection is not ready.'); return filters === undefined ? tenantQueryKey(state.projection, state.authorizationGeneration, resource) : tenantQueryKey(state.projection, state.authorizationGeneration, resource, filters) }
function FieldError({ message }: { message: string | undefined }) { return message === undefined ? null : <span className="text-destructive" role="alert">{message}</span> }

function Confirmation({ action, message, busy, onConfirm }: { action: string; message: string; busy: boolean; onConfirm: () => void }) {
  const [open, setOpen] = useState(false)
  if (!open) return <Button onClick={() => setOpen(true)} type="button" variant="secondary">{action}</Button>
  return <div aria-label={`Confirmar ${action.toLocaleLowerCase('pt-BR')}`} className="grid gap-2 rounded-md border p-3" role="group"><p>{message}</p><div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={onConfirm} type="button">Confirmar</Button><Button disabled={busy} onClick={() => setOpen(false)} type="button" variant="secondary">Cancelar</Button></div></div>
}

const reasonLabels: Record<MaintenanceReasonContext, string> = {
  CANCEL_REQUEST: 'Cancelamento de solicitação', REJECT_REQUEST: 'Rejeição de solicitação', PAUSE_WORK_ORDER: 'Pausa de ordem de serviço', CANCEL_WORK_ORDER: 'Cancelamento de ordem de serviço', RETURN_WORK_ORDER: 'Devolução de ordem de serviço',
}

type SimpleResource = 'categories' | 'subcategories' | 'reasons' | 'document-types'
interface SimpleDefinition {
  title: string; segment: string; permission: string; codeRequired: boolean
  list: (categoryId?: string, usageContext?: MaintenanceReasonContext | null) => Promise<readonly CatalogRow[]>
  get: (id: string) => Promise<CatalogRow | null>
  create: (form: CatalogFormValue) => Promise<MaintenanceCatalogCommandResult>
  update: (row: CatalogRow, form: CatalogFormValue) => Promise<MaintenanceCatalogCommandResult>
  lifecycle: (row: CatalogRow, action: 'inactivate' | 'reactivate') => Promise<MaintenanceCatalogCommandResult>
}

function CatalogForm({ definition, initial, categories, busy, submit }: { definition: SimpleDefinition; initial?: CatalogRow; categories: readonly MaintenanceCategoryLookup[]; busy: boolean; submit: (value: CatalogFormValue) => void }) {
  const needsCategory = definition.permission === 'maintenance_subcategories'; const isReason = definition.permission === 'maintenance_reasons'
  const schema = catalogFormSchema.superRefine((value, issue) => { if (definition.codeRequired && value.code.length === 0) issue.addIssue({ code: 'custom', path: ['code'], message: 'Informe um código.' }); if (needsCategory && value.categoryId.length === 0) issue.addIssue({ code: 'custom', path: ['categoryId'], message: 'Selecione a categoria.' }); if (isReason && initial === undefined && value.usageContext.length === 0) issue.addIssue({ code: 'custom', path: ['usageContext'], message: 'Selecione o contexto.' }) })
  const form = useForm<CatalogFormValue>({ resolver: zodResolver(schema), defaultValues: { code: initial?.code ?? '', name: initial?.name ?? '', description: initial?.description ?? '', reason: '', categoryId: initial?.category_id ?? '', usageContext: initial?.usage_context ?? '' } })
  return <form aria-label={initial === undefined ? `Criar ${definition.title}` : `Editar ${initial.name}`} className="mt-4 grid gap-3 rounded-lg border p-4 sm:grid-cols-2" onSubmit={(event) => { void form.handleSubmit(submit)(event) }}>
    <label className="grid gap-1 text-sm font-medium">Código<input aria-invalid={form.formState.errors.code !== undefined} aria-label="Código" className="min-h-11 rounded-md border px-3" {...form.register('code')} /><FieldError message={form.formState.errors.code?.message} /></label><label className="grid gap-1 text-sm font-medium">Nome<input aria-invalid={form.formState.errors.name !== undefined} aria-label="Nome" className="min-h-11 rounded-md border px-3" {...form.register('name')} /><FieldError message={form.formState.errors.name?.message} /></label>
    {needsCategory && <label className="grid gap-1 text-sm font-medium sm:col-span-2">Categoria<select aria-invalid={form.formState.errors.categoryId !== undefined} aria-label="Categoria" className="min-h-11 rounded-md border px-3" {...form.register('categoryId')}><option value="">Selecione</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><FieldError message={form.formState.errors.categoryId?.message} /></label>}
    {isReason && <label className="grid gap-1 text-sm font-medium sm:col-span-2">Contexto<select aria-invalid={form.formState.errors.usageContext !== undefined} aria-label="Contexto" className="min-h-11 rounded-md border px-3" disabled={initial !== undefined} {...form.register('usageContext')}><option value="">Selecione</option>{maintenanceReasonContextSchema.options.map((value) => <option key={value} value={value}>{reasonLabels[value]}</option>)}</select><FieldError message={form.formState.errors.usageContext?.message} /></label>}
    <label className="grid gap-1 text-sm font-medium sm:col-span-2">Descrição<textarea aria-invalid={form.formState.errors.description !== undefined} aria-label="Descrição" className="min-h-20 rounded-md border px-3 py-2" {...form.register('description')} /><FieldError message={form.formState.errors.description?.message} /></label><label className="grid gap-1 text-sm font-medium sm:col-span-2">Motivo da alteração<input aria-invalid={form.formState.errors.reason !== undefined} aria-label="Motivo da alteração" className="min-h-11 rounded-md border px-3" {...form.register('reason')} /><FieldError message={form.formState.errors.reason?.message} /></label><Button disabled={busy} type="submit">{busy ? 'Salvando…' : initial === undefined ? 'Criar registro' : 'Salvar alterações'}</Button>
  </form>
}

export function MaintenanceCatalogPage({ resource }: { resource: SimpleResource }) {
  const gateways = useCadastroGateways(); const gateway = gateways?.maintenanceCatalog; const { state: auth } = useAuth(); const { hasPermission } = useAuthorization(); const params = useParams(); const client = useQueryClient(); const [creating, setCreating] = useState(false); const [editing, setEditing] = useState<CatalogRow>(); const [message, setMessage] = useState<string | null>(null); const [contextFilter, setContextFilter] = useState<MaintenanceReasonContext | ''>('')
  const id = resource === 'categories' ? params.categoryId : resource === 'subcategories' ? params.subcategoryId : resource === 'reasons' ? params.reasonId : params.documentTypeId
  const definitions: Record<SimpleResource, SimpleDefinition> = {
    categories: { title: 'Categorias de Manutenção', segment: 'manutencao/categorias', permission: 'maintenance_categories', codeRequired: false, list: () => gateway!.listMaintenanceCategories(), get: (target) => gateway!.getMaintenanceCategory(target), create: (f) => gateway!.createMaintenanceCategory({ code: f.code || null, name: f.name, description: f.description || null, ...context(f.reason, 'category-create') }), update: (r, f) => gateway!.updateMaintenanceCategory({ id: r.id, expectedVersion: r.version, code: f.code || null, name: f.name, description: f.description || null, ...context(f.reason, 'category-update') }), lifecycle: (r, action) => gateway![action === 'inactivate' ? 'inactivateMaintenanceCategory' : 'reactivateMaintenanceCategory']({ id: r.id, expectedVersion: r.version, ...context('Alteração de status', 'category-status') }) },
    subcategories: { title: 'Subcategorias de Manutenção', segment: `manutencao/categorias/${params.categoryId ?? ''}/subcategorias`, permission: 'maintenance_subcategories', codeRequired: false, list: (categoryId) => gateway!.listMaintenanceSubcategories({ categoryId: categoryId ?? null }), get: (target) => gateway!.getMaintenanceSubcategory(target), create: (f) => gateway!.createMaintenanceSubcategory({ categoryId: f.categoryId, code: f.code || null, name: f.name, description: f.description || null, ...context(f.reason, 'subcategory-create') }), update: (r, f) => gateway!.updateMaintenanceSubcategory({ id: r.id, expectedVersion: r.version, categoryId: f.categoryId, code: f.code || null, name: f.name, description: f.description || null, ...context(f.reason, 'subcategory-update') }), lifecycle: (r, action) => gateway![action === 'inactivate' ? 'inactivateMaintenanceSubcategory' : 'reactivateMaintenanceSubcategory']({ id: r.id, expectedVersion: r.version, ...context('Alteração de status', 'subcategory-status') }) },
    reasons: { title: 'Motivos', segment: 'manutencao/motivos', permission: 'maintenance_reasons', codeRequired: true, list: (_category, usage) => gateway!.listMaintenanceReasons({ usageContext: usage ?? null }), get: (target) => gateway!.getMaintenanceReason(target), create: (f) => gateway!.createMaintenanceReason({ usageContext: maintenanceReasonContextSchema.parse(f.usageContext), code: f.code, name: f.name, description: f.description || null, ...context(f.reason, 'reason-create') }), update: (r, f) => gateway!.updateMaintenanceReason({ id: r.id, expectedVersion: r.version, code: f.code, name: f.name, description: f.description || null, ...context(f.reason, 'reason-update') }), lifecycle: (r, action) => gateway![action === 'inactivate' ? 'inactivateMaintenanceReason' : 'reactivateMaintenanceReason']({ id: r.id, expectedVersion: r.version, ...context('Alteração de status', 'reason-status') }) },
    'document-types': { title: 'Tipos de Documento', segment: 'cadastros/tipos-de-documento', permission: 'document_types', codeRequired: false, list: () => gateway!.listDocumentTypes(), get: (target) => gateway!.getDocumentType(target), create: (f) => gateway!.createDocumentType({ code: f.code || null, name: f.name, description: f.description || null, ...context(f.reason, 'document-type-create') }), update: (r, f) => gateway!.updateDocumentType({ id: r.id, expectedVersion: r.version, code: f.code || null, name: f.name, description: f.description || null, ...context(f.reason, 'document-type-update') }), lifecycle: (r, action) => gateway![action === 'inactivate' ? 'inactivateDocumentType' : 'reactivateDocumentType']({ id: r.id, expectedVersion: r.version, ...context('Alteração de status', 'document-type-status') }) },
  }
  const definition = definitions[resource]; const prefix = `maintenance.${definition.permission}`; const categoryId = resource === 'subcategories' ? params.categoryId : undefined
  const listPrefix = useKey(`cadastros:${resource}:list`); const listKey = useKey(`cadastros:${resource}:list`, { categoryId: categoryId ?? '', usageContext: contextFilter }); const detailKey = useKey(`cadastros:${resource}:detail`, { id: id ?? '' }); const categoryKey = useKey('cadastros:maintenance-categories:lookup')
  const canRead = hasPermission(`${prefix}.read.all_tenant`); const list = useQuery({ queryKey: listKey, enabled: gateway !== undefined && canRead && id === undefined, queryFn: () => definition.list(categoryId, contextFilter || null) }); const detail = useQuery({ queryKey: detailKey, enabled: gateway !== undefined && canRead && id !== undefined, queryFn: () => definition.get(id!) }); const categories = useQuery({ queryKey: categoryKey, enabled: gateway !== undefined && resource === 'subcategories' && hasPermission('maintenance.maintenance_categories.lookup.all_tenant'), queryFn: () => gateway!.lookupMaintenanceCategories({ limit: 100 }) })
  const refresh = () => Promise.all([client.invalidateQueries({ queryKey: listPrefix }), client.invalidateQueries({ queryKey: detailKey })])
  const mutation = useMutation({ mutationFn: ({ form, row, lifecycle }: { form?: CatalogFormValue; row?: CatalogRow; lifecycle?: boolean }) => row === undefined ? definition.create(form!) : lifecycle ? definition.lifecycle(row, row.status === 'active' ? 'inactivate' : 'reactivate') : definition.update(row, form!), onMutate: () => setMessage(null), onSuccess: async () => { setMessage('Alteração concluída.'); setCreating(false); setEditing(undefined); await refresh() }, onError: async (error) => { setMessage(safeError(error)); await refresh() } })
  if (gateway === undefined || auth.status !== 'ready') return <StatePanel title="Cadastro indisponível" description="O catálogo de manutenção não foi configurado com segurança." kind="error" />
  if (!canRead) return <StatePanel title="Sem permissão" description="Seu acesso atual não permite consultar este catálogo." kind="error" />
  const rows = id === undefined ? list.data : detail.data === null || detail.data === undefined ? [] : [detail.data]; const loading = id === undefined ? list.isLoading : detail.isLoading; const failed = id === undefined ? list.isError : detail.isError
  const listDestination = resource === 'subcategories' ? `manutencao/categorias/${params.categoryId ?? ''}` : definition.segment
  const detailDestination = (rowId: string) => resource === 'subcategories' ? `manutencao/categorias/${params.categoryId ?? ''}/subcategorias/${rowId}` : `${definition.segment}/${rowId}`
  return <><section aria-label={definition.title}><CadastroPageHeader title={definition.title} description="Gestão autorizada do catálogo de manutenção." />{id !== undefined && <Link className="mb-4 inline-flex min-h-11 items-center text-primary underline" to={canonicalTenantPath(auth.context.tenantRef, listDestination)}>Voltar à lista</Link>}{resource === 'reasons' && id === undefined && <label className="mb-4 grid gap-1 text-sm font-medium">Filtrar por contexto<select className="min-h-11 rounded-md border px-3" onChange={(event) => { const selected = event.target.value; setContextFilter(selected === '' ? '' : maintenanceReasonContextSchema.parse(selected)) }} value={contextFilter}><option value="">Todos</option>{maintenanceReasonContextSchema.options.map((value) => <option key={value} value={value}>{reasonLabels[value]}</option>)}</select></label>}{message && <p aria-live="polite">{message}</p>}{id === undefined && hasPermission(`${prefix}.create.all_tenant`) && <Button onClick={() => { setCreating(true); setEditing(undefined) }} type="button">Novo registro</Button>}{creating && <CatalogForm busy={mutation.isPending} categories={categories.data ?? []} definition={definition} submit={(form) => mutation.mutate({ form })} />}{editing && <CatalogForm busy={mutation.isPending} categories={categories.data ?? []} definition={definition} initial={editing} submit={(form) => mutation.mutate({ form, row: editing })} />}{loading ? <CadastroContentState kind="loading" /> : failed ? <CadastroContentState kind="error" onRetry={() => { void (id === undefined ? list.refetch() : detail.refetch()) }} /> : rows?.length === 0 ? <CadastroContentState kind="empty" /> : <ul className="mt-5 grid gap-3">{rows?.map((row) => <li className="rounded-lg border p-4" key={row.id}><strong>{row.name}</strong><p className="text-sm text-muted-foreground">{row.usage_context === undefined ? row.code ?? 'Sem código' : reasonLabels[row.usage_context]} · {row.status === 'active' ? 'Ativo' : 'Inativo'}</p><div className="mt-3 flex flex-wrap gap-2">{id === undefined && <Button asChild variant="secondary"><Link to={canonicalTenantPath(auth.context.tenantRef, detailDestination(row.id))}>Abrir</Link></Button>}{hasPermission(`${prefix}.update.all_tenant`) && <Button onClick={() => setEditing(row)} type="button" variant="secondary">Editar</Button>}{row.status === 'active' && hasPermission(`${prefix}.inactivate.all_tenant`) && <Confirmation action="Inativar" busy={mutation.isPending} message={`Inativar ${row.name}?`} onConfirm={() => mutation.mutate({ row, lifecycle: true })} />}{row.status === 'inactive' && hasPermission(`${prefix}.reactivate.all_tenant`) && <Confirmation action="Reativar" busy={mutation.isPending} message={`Reativar ${row.name}?`} onConfirm={() => mutation.mutate({ row, lifecycle: true })} />}</div></li>)}</ul>}</section>{resource === 'categories' && params.categoryId !== undefined && <MaintenanceCatalogPage resource="subcategories" />}</>
}

const checklistItemSchema = z.object({ position: z.number().int().min(1), prompt: z.string().trim().min(1).max(500), response_type: z.enum(checklistResponseTypeSchema.options), required: z.boolean(), instructions: z.string().trim().max(2_000) })
const checklistFormSchema = z.object({ categoryId: z.string().uuid('Selecione a categoria.'), code: z.string().trim().max(64), name: z.string().trim().min(1), description: z.string().trim().max(2_000), reason: z.string().trim().min(1), items: z.array(checklistItemSchema).min(1) })
type ChecklistFormValue = z.infer<typeof checklistFormSchema>

function ChecklistForm({ initial, categories, busy, submit }: { initial?: ChecklistTemplate; categories: readonly MaintenanceCategoryLookup[]; busy: boolean; submit: (value: ChecklistFormValue) => void }) {
  const form = useForm<ChecklistFormValue>({ resolver: zodResolver(checklistFormSchema), defaultValues: { categoryId: initial?.category_id ?? '', code: initial?.code ?? '', name: initial?.name ?? '', description: initial?.description ?? '', reason: '', items: initial?.items.map((item) => ({ position: item.position, prompt: item.prompt, response_type: item.response_type, required: item.required, instructions: item.instructions ?? '' })) ?? [{ position: 1, prompt: '', response_type: 'DONE_NOT_DONE', required: true, instructions: '' }] } })
  const items = useFieldArray({ control: form.control, name: 'items' })
  return <form aria-label={initial === undefined ? 'Criar Modelo de Checklist' : `Editar ${initial.name}`} className="mt-4 grid gap-3 rounded-lg border p-4" onSubmit={(event) => { void form.handleSubmit(submit)(event) }}>
    <label className="grid gap-1 text-sm font-medium">Categoria<select aria-invalid={form.formState.errors.categoryId !== undefined} aria-label="Categoria" className="min-h-11 rounded-md border px-3" {...form.register('categoryId')}><option value="">Selecione</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><FieldError message={form.formState.errors.categoryId?.message} /></label>
    <label className="grid gap-1 text-sm font-medium">Código<input aria-invalid={form.formState.errors.code !== undefined} aria-label="Código" className="min-h-11 rounded-md border px-3" {...form.register('code')} /><FieldError message={form.formState.errors.code?.message} /></label>
    <label className="grid gap-1 text-sm font-medium">Nome<input aria-invalid={form.formState.errors.name !== undefined} aria-label="Nome" className="min-h-11 rounded-md border px-3" {...form.register('name')} /><FieldError message={form.formState.errors.name?.message} /></label>
    <label className="grid gap-1 text-sm font-medium">Descrição<textarea aria-invalid={form.formState.errors.description !== undefined} aria-label="Descrição" className="min-h-20 rounded-md border px-3 py-2" {...form.register('description')} /><FieldError message={form.formState.errors.description?.message} /></label>
    <fieldset className="grid gap-3 rounded-md border p-3"><legend className="px-1 font-semibold">Itens da definição</legend>{items.fields.map((field, index) => <div className="grid gap-2 rounded-md border p-3 sm:grid-cols-2" key={field.id}>
      <label className="grid gap-1 text-sm font-medium">Posição<input aria-invalid={form.formState.errors.items?.[index]?.position !== undefined} aria-label="Posição" className="min-h-11 rounded-md border px-3" type="number" {...form.register(`items.${index}.position`, { valueAsNumber: true })} /><FieldError message={form.formState.errors.items?.[index]?.position?.message} /></label>
      <label className="grid gap-1 text-sm font-medium">Tipo de resposta<select aria-invalid={form.formState.errors.items?.[index]?.response_type !== undefined} aria-label="Tipo de resposta" className="min-h-11 rounded-md border px-3" {...form.register(`items.${index}.response_type`)}>{checklistResponseTypeSchema.options.map((type) => <option key={type} value={type}>{type}</option>)}</select><FieldError message={form.formState.errors.items?.[index]?.response_type?.message} /></label>
      <label className="grid gap-1 text-sm font-medium sm:col-span-2">Pergunta<input aria-invalid={form.formState.errors.items?.[index]?.prompt !== undefined} aria-label="Pergunta" className="min-h-11 rounded-md border px-3" {...form.register(`items.${index}.prompt`)} /><FieldError message={form.formState.errors.items?.[index]?.prompt?.message} /></label>
      <label className="grid gap-1 text-sm font-medium sm:col-span-2">Instruções<textarea aria-invalid={form.formState.errors.items?.[index]?.instructions !== undefined} aria-label="Instruções" className="min-h-20 rounded-md border px-3 py-2" {...form.register(`items.${index}.instructions`)} /><FieldError message={form.formState.errors.items?.[index]?.instructions?.message} /></label>
      <label className="flex min-h-11 items-center gap-2"><input type="checkbox" {...form.register(`items.${index}.required`)} />Obrigatório</label><Button disabled={items.fields.length === 1} onClick={() => items.remove(index)} type="button" variant="secondary">Remover item {index + 1}</Button>
    </div>)}<Button onClick={() => items.append({ position: items.fields.length + 1, prompt: '', response_type: 'DONE_NOT_DONE', required: true, instructions: '' })} type="button" variant="secondary">Adicionar item</Button></fieldset>
    <label className="grid gap-1 text-sm font-medium">Motivo da alteração<input aria-invalid={form.formState.errors.reason !== undefined} aria-label="Motivo da alteração" className="min-h-11 rounded-md border px-3" {...form.register('reason')} /><FieldError message={form.formState.errors.reason?.message} /></label><Button disabled={busy} type="submit">{busy ? 'Salvando…' : 'Salvar definição'}</Button>
  </form>
}

export function ChecklistTemplatesPage() {
  const gateways = useCadastroGateways(); const gateway = gateways?.maintenanceCatalog; const { state: auth } = useAuth(); const { hasPermission } = useAuthorization(); const { templateId } = useParams(); const client = useQueryClient(); const [creating, setCreating] = useState(false); const [editing, setEditing] = useState<ChecklistTemplate>(); const [message, setMessage] = useState<string | null>(null)
  const listKey = useKey('cadastros:checklist-templates:list'); const detailKey = useKey('cadastros:checklist-templates:detail', { templateId: templateId ?? '' }); const categoryKey = useKey('cadastros:maintenance-categories:lookup'); const prefix = 'maintenance.checklist_templates'
  const canRead = hasPermission(`${prefix}.read.all_tenant`); const list = useQuery({ queryKey: listKey, enabled: gateway !== undefined && canRead && templateId === undefined, queryFn: () => gateway!.listChecklistTemplates() }); const detail = useQuery({ queryKey: detailKey, enabled: gateway !== undefined && canRead && templateId !== undefined, queryFn: () => gateway!.getChecklistTemplate(templateId!) }); const categories = useQuery({ queryKey: categoryKey, enabled: gateway !== undefined && hasPermission('maintenance.maintenance_categories.lookup.all_tenant'), queryFn: () => gateway!.lookupMaintenanceCategories({ limit: 100 }) })
  const refresh = () => Promise.all([client.invalidateQueries({ queryKey: listKey }), client.invalidateQueries({ queryKey: detailKey })]); const save = useMutation({ mutationFn: (form: ChecklistFormValue) => editing === undefined ? gateway!.createChecklistTemplate({ categoryId: form.categoryId, code: form.code || null, name: form.name, description: form.description || null, items: form.items.map((item) => ({ ...item, instructions: item.instructions || null })), ...context(form.reason, 'checklist-create') }) : gateway!.updateChecklistTemplateDefinition({ id: editing.id, expectedVersion: editing.version, categoryId: form.categoryId, code: form.code || null, name: form.name, description: form.description || null, items: form.items.map((item) => ({ ...item, instructions: item.instructions || null })), ...context(form.reason, 'checklist-update') }), onMutate: () => setMessage(null), onSuccess: async () => { setMessage('Definição salva.'); setCreating(false); setEditing(undefined); await refresh() }, onError: async (error) => { setMessage(safeError(error)); await refresh() } }); const lifecycle = useMutation({ mutationFn: (row: ChecklistTemplateListItem | ChecklistTemplate) => gateway![row.status === 'active' ? 'inactivateChecklistTemplate' : 'reactivateChecklistTemplate']({ id: row.id, expectedVersion: row.version, ...context('Alteração de status', 'checklist-status') }), onMutate: () => setMessage(null), onSuccess: async () => { setMessage('Status atualizado.'); await refresh() }, onError: async (error) => { setMessage(safeError(error)); await refresh() } })
  if (gateway === undefined || auth.status !== 'ready') return <StatePanel title="Cadastro indisponível" description="O catálogo de manutenção não foi configurado." kind="error" />
  if (!canRead) return <StatePanel title="Sem permissão" description="Seu acesso atual não permite consultar modelos de checklist." kind="error" />
  const rows = templateId === undefined ? list.data : detail.data === null || detail.data === undefined ? [] : [detail.data]; const loading = templateId === undefined ? list.isLoading : detail.isLoading; const failed = templateId === undefined ? list.isError : detail.isError
  return <section aria-label="Modelos de Checklist"><CadastroPageHeader title="Modelos de Checklist" description="Definições reutilizáveis; execução de checklist não pertence a esta área." />{templateId !== undefined && <Link className="mb-4 inline-flex min-h-11 items-center text-primary underline" to={canonicalTenantPath(auth.context.tenantRef, 'manutencao/modelos-de-checklist')}>Voltar à lista</Link>}{message && <p aria-live="polite">{message}</p>}{templateId === undefined && hasPermission(`${prefix}.create.all_tenant`) && <Button onClick={() => setCreating(true)} type="button">Novo modelo</Button>}{creating && <ChecklistForm busy={save.isPending} categories={categories.data ?? []} submit={(form) => save.mutate(form)} />}{editing && <ChecklistForm busy={save.isPending} categories={categories.data ?? []} initial={editing} submit={(form) => save.mutate(form)} />}{loading ? <CadastroContentState kind="loading" /> : failed ? <CadastroContentState kind="error" onRetry={() => { void (templateId === undefined ? list.refetch() : detail.refetch()) }} /> : rows?.length === 0 ? <CadastroContentState kind="empty" /> : <ul className="mt-5 grid gap-3">{rows?.map((row) => <li className="rounded-lg border p-4" key={row.id}><strong>{row.name}</strong><p>{'item_count' in row ? `${row.item_count} itens` : `${row.items.length} itens`} · {row.status === 'active' ? 'Ativo' : 'Inativo'}</p>{'items' in row && <ol className="mt-2 list-decimal pl-6">{row.items.map((item) => <li key={item.id}>{item.position}. {item.prompt} — {item.response_type}</li>)}</ol>}<div className="mt-3 flex flex-wrap gap-2">{templateId === undefined && <Button asChild variant="secondary"><Link to={canonicalTenantPath(auth.context.tenantRef, `manutencao/modelos-de-checklist/${row.id}`)}>Abrir</Link></Button>}{templateId !== undefined && hasPermission(`${prefix}.update.all_tenant`) && 'items' in row && <Button onClick={() => setEditing(row)} type="button" variant="secondary">Editar definição</Button>}{row.status === 'active' && hasPermission(`${prefix}.inactivate.all_tenant`) && <Confirmation action="Inativar" busy={lifecycle.isPending} message={`Inativar ${row.name}?`} onConfirm={() => lifecycle.mutate(row)} />}{row.status === 'inactive' && hasPermission(`${prefix}.reactivate.all_tenant`) && <Confirmation action="Reativar" busy={lifecycle.isPending} message={`Reativar ${row.name}?`} onConfirm={() => lifecycle.mutate(row)} />}</div></li>)}</ul>}</section>
}

export function CatalogTemplatePage() {
  const gateway = useCadastroGateways()?.maintenanceCatalog; const { hasPermission } = useAuthorization(); const client = useQueryClient(); const previewKey = useKey('cadastros:template-cw:preview'); const categoryKey = useKey('cadastros:categories:list'); const subcategoryKey = useKey('cadastros:subcategories:list'); const [message, setMessage] = useState<string | null>(null)
  const canApply = hasPermission('maintenance.catalog_templates.apply.all_tenant'); const preview = useQuery({ queryKey: previewKey, enabled: gateway !== undefined && canApply, queryFn: () => gateway!.getCatalogTemplatePreview({ templateKey: 'cw_maintenance_taxonomy', templateVersion: 1 }) }); const apply = useMutation({ mutationFn: () => gateway!.applyCatalogTemplate({ templateKey: 'cw_maintenance_taxonomy', templateVersion: 1, ...context('Aplicação explícita do modelo CW', 'template-cw-apply') }), onMutate: () => setMessage(null), onSuccess: async () => { setMessage('Modelo CW aplicado. O catálogo criado pertence ao empreendimento.'); await Promise.all([client.invalidateQueries({ queryKey: previewKey }), client.invalidateQueries({ queryKey: categoryKey }), client.invalidateQueries({ queryKey: subcategoryKey })]) }, onError: async (error) => { setMessage(safeError(error)); await client.invalidateQueries({ queryKey: previewKey }) } })
  if (gateway === undefined) return <StatePanel title="Cadastro indisponível" description="O Template CW não foi configurado." kind="error" />
  if (!canApply) return <StatePanel title="Sem permissão" description="Seu acesso atual não permite aplicar o modelo CW." kind="error" />
  return <section aria-label="Template CW"><CadastroPageHeader title="Template CW" description="Opção para iniciar uma taxonomia vazia com cópias próprias do modelo CW." />{message && <p aria-live="polite">{message}</p>}{preview.isLoading ? <CadastroContentState kind="loading" /> : preview.isError ? <CadastroContentState kind="error" onRetry={() => { void preview.refetch() }} /> : <div className="grid gap-4 rounded-lg border p-4"><p>Modelo opcional e imutável: {preview.data?.category_count} categorias e {preview.data?.subcategory_count} subcategorias.</p><p>O servidor aplica somente em taxonomia elegível. Não há merge, sincronização ou atualização automática.</p><Confirmation action="Aplicar modelo CW" busy={apply.isPending} message="Aplicar explicitamente o modelo CW à taxonomia vazia deste empreendimento?" onConfirm={() => apply.mutate()} /></div>}</section>
}
